export const QUOTES: string[] = [
  'Không có bài nào khó, chỉ có người chưa đủ kiên nhẫn.',
  'Đọc đề kỹ 3 lần trước khi code.',
  'Test tay trước, submit sau.',
  'Subtask 1 điểm nào cũng phải lấy.',
  'Bug không tự tìm được mình — hãy dùng gdb.',
  'Brute force trước, tối ưu sau.',
  'Mỗi bài giải được là một bước gần hơn đến NBK.',
  'Codeforces hôm nay, IOI ngày mai.',
  'Người giỏi không phải không sai — họ debug nhanh hơn.',
  'Recursive đẹp, iterative nhanh — biết dùng đúng lúc.',
  'Luôn xét trường hợp N=0, N=1 trước.',
  'Overflow int32 — nhớ dùng long long.',
  'Complexity O(N²) với N=10^5 là TLE đấy.',
  'Học thuật toán không phải để nhớ — mà để nhận ra.',
  'Mỗi WA là một bài học, không phải thất bại.',
  'Thi xong mới biết mình yếu chỗ nào.',
  'Đừng sợ bài khó — sợ bài khó không dám nghĩ.',
  'Cây phân đoạn giải được nhiều hơn bạn nghĩ.',
  'Quy hoạch động: state, transition, base case.',
  'Đà Nẵng 2026 — NBK chuyên Tin — mục tiêu!',
]
