#!/usr/bin/env python3
"""
DP classics — generate 20 internal problems covering the full set of
classical Dynamic Programming patterns that HSG lop 9 students need.

Coverage (5 topics x 4 new problems = 20 problems):

  dp-intro        : dp-min-jumps, dp-decode-ways, dp-paint-fence, dp-max-prod-subarr
  dp-knapsack     : dp-rod-cut, dp-egg-drop, dp-knap-bounded, dp-target-sum
  dp-lis-lcs      : dp-lps, dp-lps-substring, dp-lcs-print, dp-russian-doll
  dp-grid         : dp-tile-2xn, dp-tile-3xn, dp-cherry-pickup, dp-paths-king
  tree-dp-intro   : tdp-knapsack, tdp-min-vcover, tdp-paths-sum, tdp-color-tree

Each problem has:
  - Vietnamese statement
  - 3 subtasks (small/medium/large) with summing points = 100
  - 18-21 test cases generated by deterministic random + Python brute solver
  - 3 hints (one per subtask)
  - editorial + solutionSketch

Run:  python3 scripts/build_dp_problems.py
Writes JSON files into public/data/problems/ and patches roadmap.json
(appends new slugs to existing problems[]) + rebuilds index.json.
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = ROOT / "public" / "data" / "problems"
ROADMAP = ROOT / "public" / "data" / "roadmap.json"
INDEX = PROBLEMS_DIR / "index.json"

CREATED_AT = "2026-05-26"


# ---------------------------------------------------------------------------
# Generic helpers (mirrors build_phase2_problems.py)
# ---------------------------------------------------------------------------
def write_problem(problem: dict) -> None:
    """Validate basic invariants then dump to public/data/problems/<slug>.json."""
    slug = problem["slug"]
    subtask_ids = {st["id"] for st in problem["subtasks"]}
    for tc in problem["testCases"]:
        assert tc["subtaskId"] in subtask_ids, f"{slug}: tc {tc['id']} -> unknown sub {tc['subtaskId']}"
    pts = sum(st["points"] for st in problem["subtasks"])
    assert pts == 100, f"{slug}: subtask points sum to {pts}, expected 100"
    out = PROBLEMS_DIR / f"{slug}.json"
    out.write_text(json.dumps(problem, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def base_problem(
    slug: str,
    title: str,
    title_en: str,
    topic_id: str,
    tier: str,
    skills: list,
    difficulty: int,
    tags: list,
    statement: str,
    vn_pattern: str,
    subtasks: list,
    samples: list,
    test_cases: list,
    hints: list,
    editorial: str,
    sketch: str,
    time_limit_s: int = 1,
    memory_mb: int = 256,
) -> dict:
    return {
        "slug": slug,
        "title": title,
        "titleEn": title_en,
        "module": "roadmap",
        "topicId": topic_id,
        "tier": tier,
        "skills": skills,
        "difficulty": difficulty,
        "maxStars": 3,
        "tags": tags,
        "source": "Bài tự build (DP classics)",
        "isExternal": False,
        "statement": statement,
        "vnPattern": vn_pattern,
        "fileIO": {"inputFile": "stdin", "outputFile": "stdout"},
        "subtasks": subtasks,
        "samples": samples,
        "testCases": test_cases,
        "hints": hints,
        "editorial": editorial,
        "solutionSketch": sketch,
        "timeLimit": time_limit_s,
        "memoryLimit": memory_mb,
        "timeLimitMs": time_limit_s * 1000,
        "memoryLimitKB": memory_mb * 1024,
        "createdAt": CREATED_AT,
    }


def generate_cases(slug: str, subtasks: list, solver: Callable[[str], str]) -> tuple:
    rng = random.Random(hash(slug) & 0xFFFFFFFF)
    cases = []
    samples = []
    tc_id = 0
    for st in subtasks:
        for _ in range(st["nCases"]):
            tc_id += 1
            inp = st["gen"](rng)
            out = solver(inp)
            cases.append({
                "id": f"tc{tc_id:02d}",
                "subtaskId": st["id"],
                "input": inp,
                "output": out,
            })
            if st["id"] == subtasks[0]["id"] and len(samples) < 2:
                samples.append({
                    "id": f"sample{len(samples) + 1}",
                    "input": inp,
                    "output": out,
                })
    return cases, samples


def strip_gen(subtasks: list) -> None:
    for st in subtasks:
        st.pop("gen", None)
        st.pop("nCases", None)


# ===========================================================================
# dp-intro
# ===========================================================================
def build_dp_min_jumps():
    slug = "dp-min-jumps"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        a = list(map(int, toks[1:1 + n]))
        INF = 10 ** 9
        dp = [INF] * n
        dp[0] = 0
        for i in range(n):
            if dp[i] == INF:
                continue
            for k in range(1, a[i] + 1):
                j = i + k
                if j >= n:
                    break
                if dp[i] + 1 < dp[j]:
                    dp[j] = dp[i] + 1
        return ("-1" if dp[n - 1] == INF else str(dp[n - 1]))

    def gen(rng, n_lo, n_hi, v_lo, v_hi):
        n = rng.randint(n_lo, n_hi)
        a = [rng.randint(v_lo, v_hi) for _ in range(n)]
        a[-1] = rng.randint(0, v_hi)
        return f"{n}\n{' '.join(map(str, a))}\n"

    def g1(rng): return gen(rng, 2, 10, 0, 4)
    def g2(rng): return gen(rng, 30, 80, 0, 6)
    def g3(rng): return gen(rng, 200, 400, 0, 8)

    subtasks = [
        {"id": "st1", "title": "N ≤ 10", "points": 30, "constraint": "1 ≤ N ≤ 10; 0 ≤ a[i] ≤ 4", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 30, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 500", "points": 40, "constraint": "1 ≤ N ≤ 500", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho mảng `a[0..n-1]`. Tại vị trí `i`, bạn có thể nhảy tới một trong các vị trí "
        "`i+1, i+2, ..., i+a[i]` (miễn không vượt quá `n-1`). Hãy tìm **số bước nhảy ít "
        "nhất** để đi từ vị trí 0 đến vị trí `n-1`. Nếu không đến được, in `-1`.\n\n"
        "**Input**: dòng 1 chứa N; dòng 2 chứa N số `a[i]`.\n\n"
        "**Output**: 1 số nguyên duy nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Đặt dp[i] = số bước tối thiểu đến i. Chuyển từ dp[i] sang dp[i+1..i+a[i]].", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "O(N·A) đủ AC: hai vòng for, cập nhật min.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Có thể giải O(N) bằng BFS / greedy farthest, nhưng O(N²) vẫn AC trong giới hạn này.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Số bước nhảy tối thiểu",
        title_en="Min Jumps to Reach End",
        topic_id="dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "dp-intro"], statement=statement,
        vn_pattern="DP 1D, transition tới các vị trí gần.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[i] = bước nhảy ít nhất tới i. Khởi tạo dp[0]=0, các dp[i]=∞. Lặp i từ 0 đến n-1, với mỗi j ∈ [i+1, i+a[i]], cập nhật dp[j] = min(dp[j], dp[i]+1). Đáp án dp[n-1]; nếu ∞ thì -1. Độ phức tạp O(N·A).",
        sketch="// dp[0]=0; for i,j: dp[j]=min(dp[j], dp[i]+1)",
    )


def build_dp_decode_ways():
    slug = "dp-decode-ways"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        s = inp.strip()
        n = len(s)
        if n == 0:
            return "0"
        dp = [0] * (n + 1)
        dp[0] = 1
        for i in range(1, n + 1):
            if s[i - 1] != "0":
                dp[i] = (dp[i] + dp[i - 1]) % MOD
            if i >= 2:
                two = int(s[i - 2:i])
                if 10 <= two <= 26:
                    dp[i] = (dp[i] + dp[i - 2]) % MOD
        return str(dp[n])

    def gen(rng, n_lo, n_hi):
        n = rng.randint(n_lo, n_hi)
        # avoid leading 0 to keep things realistic; mostly digits 1-9 then occasionally 0
        digits = []
        for i in range(n):
            if i == 0:
                digits.append(str(rng.randint(1, 9)))
            else:
                # mostly 1..9, 20% chance 0 if previous decodes 1-2
                if rng.random() < 0.2 and digits[-1] in "12":
                    digits.append("0")
                else:
                    digits.append(str(rng.randint(1, 9)))
        return "".join(digits) + "\n"

    def g1(rng): return gen(rng, 1, 8)
    def g2(rng): return gen(rng, 30, 80)
    def g3(rng): return gen(rng, 500, 1000)

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 8", "points": 25, "constraint": "1 ≤ |S| ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 100", "points": 35, "constraint": "1 ≤ |S| ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 1000", "points": 40, "constraint": "1 ≤ |S| ≤ 1000", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Bộ mã hoá: `A=1, B=2, ..., Z=26`. Cho xâu chữ số `S`, hãy đếm số cách giải mã `S` thành "
        "xâu chữ cái (in modulo 10^9+7). Ví dụ `\"12\"` → 2 cách: `AB` (1,2) hoặc `L` (12).\n\n"
        "**Input**: dòng 1 chứa xâu `S`.\n\n"
        "**Output**: số cách (mod 10^9+7)."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê đệ quy tất cả phân hoạch hợp lệ.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "dp[i] = số cách giải mã S[0..i-1]; transition lấy 1 hoặc 2 chữ số.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "O(N) là đủ; chú ý ký tự '0' chỉ hợp lệ khi đứng sau '1' hoặc '2'.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đếm số cách giải mã (A-Z)",
        title_en="Decode Ways",
        topic_id="dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "dp-intro", "counting"], statement=statement,
        vn_pattern="DP 1D đếm cách; xét cuối 1 hoặc 2 chữ số.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[i] = số cách giải mã S[:i]. dp[0]=1. Nếu S[i-1]!='0' thì dp[i]+=dp[i-1]. Nếu i≥2 và 10≤int(S[i-2:i])≤26 thì dp[i]+=dp[i-2]. Modulo 10^9+7. O(N).",
        sketch="// dp[i]+=dp[i-1] if s[i-1]!='0'; dp[i]+=dp[i-2] if 10<=int(s[i-2:i])<=26",
    )


def build_dp_paint_fence():
    slug = "dp-paint-fence"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        n, k = map(int, inp.split())
        if n == 0:
            return "0"
        if n == 1:
            return str(k % MOD)
        same = k
        diff = k * (k - 1)
        for _ in range(3, n + 1):
            new_same = diff
            new_diff = (same + diff) * (k - 1) % MOD
            same, diff = new_same % MOD, new_diff
        return str((same + diff) % MOD)

    def gen(rng, n_hi, k_hi):
        n = rng.randint(1, n_hi)
        k = rng.randint(1, k_hi)
        return f"{n} {k}\n"

    def g1(rng): return gen(rng, 6, 4)
    def g2(rng): return gen(rng, 100, 50)
    def g3(rng): return gen(rng, 10**6, 1000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 6, K ≤ 4", "points": 25, "constraint": "1 ≤ N ≤ 6; 1 ≤ K ≤ 4", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 100, K ≤ 50", "points": 30, "constraint": "1 ≤ N ≤ 100; 1 ≤ K ≤ 50", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^6, K ≤ 1000", "points": 45, "constraint": "1 ≤ N ≤ 10^6; 1 ≤ K ≤ 1000", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Sơn `N` thanh hàng rào với `K` màu. Ràng buộc: **không** được có 3 thanh liên tiếp cùng màu. "
        "Đếm số cách sơn, in modulo 10^9+7.\n\n"
        "**Input**: 1 dòng chứa 2 số `N`, `K`.\n\n"
        "**Output**: số cách."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê tất cả K^N cách rồi loại.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "same[i]/diff[i] = cách sơn i thanh kết thúc bằng 2 thanh cùng / khác màu.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Công thức: total[i]=same+diff; same'=diff; diff'=total*(K-1). O(N).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Sơn hàng rào K màu (không 3 thanh liền cùng màu)",
        title_en="Paint Fence",
        topic_id="dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "dp-intro", "counting"], statement=statement,
        vn_pattern="DP đếm cách; trạng thái = (cùng màu 2 cuối / khác màu 2 cuối).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Gọi `same` là số cách N thanh kết thúc bằng 2 thanh cùng màu, `diff` là số cách kết thúc khác màu. Khởi tạo (N=2): same=K, diff=K(K-1). Chuyển: new_same=diff (thanh mới giống thanh trước), new_diff=(same+diff)(K-1). Đáp án same+diff. O(N).",
        sketch="// same,diff loops; new_same=diff; new_diff=(same+diff)*(k-1)",
    )


def build_dp_max_prod_subarr():
    slug = "dp-max-prod-subarr"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        a = list(map(int, toks[1:1 + n]))
        if not a:
            return "0"
        best = cur_max = cur_min = a[0]
        for x in a[1:]:
            cands = (x, cur_max * x, cur_min * x)
            cur_max = max(cands)
            cur_min = min(cands)
            if cur_max > best:
                best = cur_max
        return str(best)

    def gen(rng, n_lo, n_hi, lo, hi):
        n = rng.randint(n_lo, n_hi)
        a = [rng.randint(lo, hi) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, a))}\n"

    def g1(rng): return gen(rng, 1, 8, -5, 5)
    def g2(rng): return gen(rng, 50, 200, -10, 10)
    def g3(rng): return gen(rng, 1000, 5000, -10, 10)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8; |a[i]| ≤ 5", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 200", "points": 30, "constraint": "1 ≤ N ≤ 200; |a[i]| ≤ 10", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 5000", "points": 45, "constraint": "1 ≤ N ≤ 5000; |a[i]| ≤ 10", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho dãy `N` số nguyên (có thể âm). Tìm **tích lớn nhất** của một dãy con liên tiếp (≥1 phần tử).\n\n"
        "**Input**: dòng 1 chứa N; dòng 2 chứa N số.\n\n"
        "**Output**: 1 số nguyên duy nhất là tích lớn nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Vét cạn tất cả đoạn O(N²) hoặc O(N³).", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Kadane biến thể: số âm khi nhân số âm thành dương, nên giữ cả max và min.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Duyệt 1 lần O(N), cập nhật cur_max/cur_min.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Tích lớn nhất của dãy con liên tiếp",
        title_en="Maximum Product Subarray",
        topic_id="dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "dp-intro", "kadane"], statement=statement,
        vn_pattern="Kadane biến thể; vì có số âm phải giữ cả min lẫn max.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Duyệt mảng, giữ `cur_max`, `cur_min` là max/min của tích các đoạn kết thúc tại i. Khi gặp số âm, tích tối thiểu có thể trở thành tối đa, nên ta cần cả hai. Công thức: cur_max = max(x, cur_max*x, cur_min*x), cur_min tương tự với min. Đáp án = max cur_max. O(N).",
        sketch="// cur_max,cur_min; ans=max(ans,cur_max); update both with max/min of {x, cur_max*x, cur_min*x}",
    )


# ===========================================================================
# dp-knapsack
# ===========================================================================
def build_dp_rod_cut():
    slug = "dp-rod-cut"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        p = list(map(int, toks[1:1 + n]))
        dp = [0] * (n + 1)
        for j in range(1, n + 1):
            best = 0
            for k in range(1, j + 1):
                cand = p[k - 1] + dp[j - k]
                if cand > best:
                    best = cand
            dp[j] = best
        return str(dp[n])

    def gen(rng, n_lo, n_hi, p_hi):
        n = rng.randint(n_lo, n_hi)
        p = [rng.randint(1, p_hi) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, p))}\n"

    def g1(rng): return gen(rng, 1, 8, 20)
    def g2(rng): return gen(rng, 30, 80, 100)
    def g3(rng): return gen(rng, 300, 600, 1000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 600", "points": 40, "constraint": "1 ≤ N ≤ 600", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho thanh sắt dài `N`. Cắt thanh thành các đoạn nguyên dương, đoạn dài `k` bán được `p[k]`. "
        "Tìm tổng giá trị tối đa thu được khi cắt thanh tối ưu (có thể không cắt = bán nguyên thanh).\n\n"
        "**Input**: dòng 1 chứa `N`; dòng 2 chứa `p[1], p[2], ..., p[N]`.\n\n"
        "**Output**: 1 số nguyên duy nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê 2^(N-1) cách cắt.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Bài toán unbounded knapsack: dp[j] = giá trị tối đa khi cắt thanh dài j.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "dp[j] = max(p[k] + dp[j-k]) với k=1..j. O(N²).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Cắt thanh sắt tối ưu (Rod Cutting)",
        title_en="Rod Cutting",
        topic_id="dp-knapsack", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "knapsack", "rod-cutting"], statement=statement,
        vn_pattern="Unbounded knapsack: chọn đoạn cắt có thể lặp.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Đây là biến thể unbounded knapsack. dp[j] = giá trị tối đa cắt được thanh dài j. dp[0]=0. dp[j] = max(p[k] + dp[j-k]) với k=1..j. Đáp án dp[N]. O(N²).",
        sketch="// dp[j] = max(p[k] + dp[j-k]) for k=1..j",
    )


def build_dp_egg_drop():
    slug = "dp-egg-drop"

    def solve(inp: str) -> str:
        k, n = map(int, inp.split())
        INF = 10 ** 9
        # dp[i][j] = min worst-case throws with i eggs and j floors
        dp = [[0] * (n + 1) for _ in range(k + 1)]
        for j in range(1, n + 1):
            dp[1][j] = j
        for i in range(2, k + 1):
            for j in range(1, n + 1):
                best = INF
                for x in range(1, j + 1):
                    cur = 1 + max(dp[i - 1][x - 1], dp[i][j - x])
                    if cur < best:
                        best = cur
                dp[i][j] = best
        return str(dp[k][n])

    def gen(rng, k_hi, n_hi):
        k = rng.randint(1, k_hi)
        n = rng.randint(1, n_hi)
        return f"{k} {n}\n"

    def g1(rng): return gen(rng, 2, 8)
    def g2(rng): return gen(rng, 4, 40)
    def g3(rng): return gen(rng, 6, 150)

    subtasks = [
        {"id": "st1", "title": "K ≤ 2, N ≤ 8", "points": 25, "constraint": "1 ≤ K ≤ 2; 1 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "K ≤ 4, N ≤ 40", "points": 35, "constraint": "1 ≤ K ≤ 4; 1 ≤ N ≤ 40", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "K ≤ 6, N ≤ 150", "points": 40, "constraint": "1 ≤ K ≤ 6; 1 ≤ N ≤ 150", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Bạn có `K` quả trứng và toà nhà `N` tầng. Có một tầng *tới hạn* `f` (0 ≤ f ≤ N): "
        "thả trứng từ tầng > f thì vỡ, ≤ f thì nguyên. Trứng nguyên có thể dùng tiếp. "
        "Hãy tìm **số lần thả trong tình huống xấu nhất** ít nhất để xác định chính xác `f`.\n\n"
        "**Input**: 1 dòng chứa `K`, `N`.\n\n"
        "**Output**: 1 số nguyên duy nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "K=1: phải thử tuần tự, đáp án N. K=2 dùng DP nhỏ.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "dp[i][j] = min worst-case với i trứng, j tầng. Thử thả tại tầng x.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Công thức: dp[i][j] = min(1 + max(dp[i-1][x-1], dp[i][j-x])) với x=1..j. O(K·N²).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Bài toán thả trứng (Egg Dropping)",
        title_en="Egg Dropping Puzzle",
        topic_id="dp-knapsack", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["dp", "minimax", "classic"], statement=statement,
        vn_pattern="DP minimax 2 chiều; trạng thái (trứng còn, tầng còn).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[i][j] = số lần thả tối thiểu trong worst-case với i trứng, j tầng. Base: dp[1][j]=j; dp[i][0]=0. Trans: dp[i][j] = min trên x=1..j của 1 + max(dp[i-1][x-1] (vỡ → còn i-1 trứng, x-1 tầng dưới), dp[i][j-x] (nguyên → còn i trứng, j-x tầng trên)). O(K·N²) đủ AC trong giới hạn này.",
        sketch="// dp[i][j] = min over x: 1 + max(dp[i-1][x-1], dp[i][j-x])",
        time_limit_s=2,
    )


def build_dp_knap_bounded():
    slug = "dp-knap-bounded"

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        W = int(toks[idx]); idx += 1
        items = []
        for _ in range(n):
            w = int(toks[idx]); idx += 1
            v = int(toks[idx]); idx += 1
            c = int(toks[idx]); idx += 1
            items.append((w, v, c))
        dp = [0] * (W + 1)
        for w, v, c in items:
            for j in range(W, -1, -1):
                # try using k = 1..c copies
                k = 1
                while k <= c and k * w <= j:
                    cand = dp[j - k * w] + k * v
                    if cand > dp[j]:
                        dp[j] = cand
                    k += 1
        return str(max(dp))

    def gen(rng, n_hi, W_hi, w_hi, v_hi, c_hi):
        n = rng.randint(1, n_hi)
        W = rng.randint(1, W_hi)
        lines = [f"{n} {W}"]
        for _ in range(n):
            w = rng.randint(1, w_hi)
            v = rng.randint(1, v_hi)
            c = rng.randint(1, c_hi)
            lines.append(f"{w} {v} {c}")
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 5, 20, 10, 30, 3)
    def g2(rng): return gen(rng, 20, 80, 30, 100, 5)
    def g3(rng): return gen(rng, 50, 300, 50, 200, 5)

    subtasks = [
        {"id": "st1", "title": "N ≤ 5, W ≤ 20, c ≤ 3", "points": 25, "constraint": "1 ≤ N ≤ 5; W ≤ 20; c[i] ≤ 3", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 20, W ≤ 80", "points": 30, "constraint": "1 ≤ N ≤ 20; W ≤ 80; c[i] ≤ 5", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 50, W ≤ 300", "points": 45, "constraint": "1 ≤ N ≤ 50; W ≤ 300; c[i] ≤ 5", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Túi sức chứa `W`. Có `N` loại món; loại `i` cân `w[i]`, giá trị `v[i]`, có **tối đa `c[i]` "
        "bản sao**. Tìm tổng giá trị lớn nhất khi chọn các món sao cho tổng cân ≤ W.\n\n"
        "**Input**: dòng 1 chứa `N`, `W`; N dòng tiếp theo, mỗi dòng 3 số `w[i] v[i] c[i]`.\n\n"
        "**Output**: 1 số nguyên duy nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Vét cạn tất cả cách lấy mỗi món 0..c[i] lần.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Biến thành knapsack 0/1 bằng cách 'tách' món thành c[i] bản sao.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "DP O(N·W·max_c) hoặc dùng binary splitting (1,2,4,...) để giảm số lần lặp.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Túi có giới hạn số bản sao (Bounded Knapsack)",
        title_en="Bounded Knapsack",
        topic_id="dp-knapsack", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "knapsack", "bounded"], statement=statement,
        vn_pattern="0/1 knapsack mở rộng: mỗi món có c[i] bản.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[j] = giá trị tối đa khi tổng cân = j. Với mỗi món (w,v,c), duyệt j từ W về 0; thử dùng k=1..c bản, j-k·w≥0: dp[j] = max(dp[j], dp[j-k·w] + k·v). O(N·W·max_c). Có thể tăng tốc bằng binary splitting (1,2,4,..., c-2^t) → O(N·W·log max_c).",
        sketch="// for each (w,v,c): for j W..0: for k=1..c, k*w<=j: dp[j]=max(dp[j], dp[j-k*w]+k*v)",
    )


def build_dp_target_sum():
    slug = "dp-target-sum"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        T = int(toks[1])
        a = list(map(int, toks[2:2 + n]))
        s = sum(a)
        # target +/- a[i] = T ⇒ subset P with sum(P) = (s+T)/2
        if (s + T) % 2 != 0 or s + T < 0 or s < abs(T):
            return "0"
        S = (s + T) // 2
        dp = [0] * (S + 1)
        dp[0] = 1
        for x in a:
            for j in range(S, x - 1, -1):
                dp[j] = (dp[j] + dp[j - x]) % MOD
        return str(dp[S])

    def gen(rng, n_lo, n_hi, v_hi, T_abs):
        n = rng.randint(n_lo, n_hi)
        a = [rng.randint(0, v_hi) for _ in range(n)]
        s = sum(a)
        # bound T so |T| ≤ s
        if s == 0:
            T = 0
        else:
            T = rng.randint(-min(s, T_abs), min(s, T_abs))
        return f"{n} {T}\n{' '.join(map(str, a))}\n"

    def g1(rng): return gen(rng, 1, 8, 5, 20)
    def g2(rng): return gen(rng, 30, 60, 10, 100)
    def g3(rng): return gen(rng, 100, 200, 20, 500)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 30, "constraint": "1 ≤ N ≤ 8; 0 ≤ a[i] ≤ 5", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 60, |T| ≤ 100", "points": 30, "constraint": "1 ≤ N ≤ 60; 0 ≤ a[i] ≤ 10; |T| ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 200, |T| ≤ 500", "points": 40, "constraint": "1 ≤ N ≤ 200; 0 ≤ a[i] ≤ 20; |T| ≤ 500", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho dãy `N` số nguyên không âm `a[1..N]` và số nguyên `T`. Đặt dấu `+` hoặc `-` trước "
        "mỗi số sao cho tổng đại số bằng `T`. Đếm số cách (mod 10^9+7).\n\n"
        "**Input**: dòng 1 chứa `N`, `T`; dòng 2 chứa N số `a[i]`.\n\n"
        "**Output**: số cách."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê 2^N cách đặt dấu.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Đặt P = tập dấu +, N = tập dấu −. sum(P)−sum(N)=T, sum(P)+sum(N)=S. Suy ra sum(P)=(S+T)/2.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Quy về đếm số tập con tổng (S+T)/2. DP 1 chiều như subset count.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đặt dấu +/− đạt tổng đích",
        title_en="Target Sum",
        topic_id="dp-knapsack", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "knapsack", "counting"], statement=statement,
        vn_pattern="Quy về subset-sum count.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Gọi P = các phần tử mang dấu +, N = các phần tử mang dấu −. Có sum(P) − sum(N) = T và sum(P)+sum(N)=S. Suy ra sum(P)=(S+T)/2 = S'. Nếu (S+T) lẻ hoặc S'<0 → 0. Còn lại: đếm số tập con tổng S' bằng DP 1D như subset-count. O(N·S').",
        sketch="// S'=(S+T)/2; dp[0]=1; for x: for j=S'..x: dp[j]+=dp[j-x] mod",
    )


# ===========================================================================
# dp-lis-lcs
# ===========================================================================
def build_dp_lps():
    slug = "dp-lps"

    def solve(inp: str) -> str:
        s = inp.strip()
        n = len(s)
        if n == 0:
            return "0"
        dp = [[0] * n for _ in range(n)]
        for i in range(n):
            dp[i][i] = 1
        for L in range(2, n + 1):
            for i in range(n - L + 1):
                j = i + L - 1
                if s[i] == s[j]:
                    dp[i][j] = (dp[i + 1][j - 1] if L > 2 else 0) + 2
                else:
                    dp[i][j] = max(dp[i + 1][j], dp[i][j - 1])
        return str(dp[0][n - 1])

    def gen(rng, n_lo, n_hi, alpha):
        n = rng.randint(n_lo, n_hi)
        s = "".join(rng.choice("abcdefgh"[:alpha]) for _ in range(n))
        return s + "\n"

    def g1(rng): return gen(rng, 1, 8, 3)
    def g2(rng): return gen(rng, 30, 80, 4)
    def g3(rng): return gen(rng, 300, 600, 6)

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 8", "points": 25, "constraint": "1 ≤ |S| ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 100", "points": 35, "constraint": "1 ≤ |S| ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 600", "points": 40, "constraint": "1 ≤ |S| ≤ 600", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho xâu `S`. Hãy tìm **độ dài** dãy con palindrome dài nhất (LPS — Longest Palindromic Subsequence). "
        "Dãy con là chuỗi thu được từ S bằng cách xoá 0 hoặc nhiều ký tự, giữ thứ tự.\n\n"
        "**Input**: 1 dòng chứa xâu `S`.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Vét cạn 2^|S| dãy con, check palindrome.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "LPS(S) = LCS(S, reverse(S)). Áp dụng DP LCS.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "DP interval: dp[i][j] = LPS trong S[i..j]. Trans dùng s[i]?=s[j].", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Dãy con palindrome dài nhất (LPS)",
        title_en="Longest Palindromic Subsequence",
        topic_id="dp-lis-lcs", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "lcs", "palindrome", "interval-dp"], statement=statement,
        vn_pattern="Interval DP trên đoạn xâu; trans tách 2 đầu.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[i][j] = LPS độ dài trong S[i..j]. Base: dp[i][i]=1. Trans: nếu S[i]=S[j] thì dp[i][j] = dp[i+1][j-1] + 2 (với L=2 → 2). Ngược lại dp[i][j] = max(dp[i+1][j], dp[i][j-1]). Lặp theo L=2..n. O(n²).",
        sketch="// dp[i][i]=1; for L=2..n: dp[i][j]=s[i]==s[j]?dp[i+1][j-1]+2:max(dp[i+1][j],dp[i][j-1])",
    )


def build_dp_lps_substring():
    slug = "dp-lps-substring"

    def solve(inp: str) -> str:
        s = inp.strip()
        n = len(s)
        if n == 0:
            return "0"
        best = 1
        # expand around center
        for c in range(n):
            l, r = c, c
            while l >= 0 and r < n and s[l] == s[r]:
                l -= 1
                r += 1
            best = max(best, r - l - 1)
            l, r = c, c + 1
            while l >= 0 and r < n and s[l] == s[r]:
                l -= 1
                r += 1
            best = max(best, r - l - 1)
        return str(best)

    def gen(rng, n_lo, n_hi, alpha):
        n = rng.randint(n_lo, n_hi)
        s = "".join(rng.choice("abcdef"[:alpha]) for _ in range(n))
        return s + "\n"

    def g1(rng): return gen(rng, 1, 10, 3)
    def g2(rng): return gen(rng, 50, 200, 4)
    def g3(rng): return gen(rng, 1500, 3000, 5)

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 10", "points": 25, "constraint": "1 ≤ |S| ≤ 10", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 200", "points": 30, "constraint": "1 ≤ |S| ≤ 200", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 3000", "points": 45, "constraint": "1 ≤ |S| ≤ 3000", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho xâu `S`. Tìm **độ dài xâu con liên tiếp** lớn nhất là palindrome.\n\n"
        "**Input**: 1 dòng chứa `S`.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Xét mọi đoạn O(N²) và check palindrome O(N) → O(N³).", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DP isPal[i][j] = palindrome? Trans theo độ dài L. O(N²).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Mở rộng quanh tâm (2N-1 tâm), mỗi tâm O(N). Tổng O(N²).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Xâu con palindrome dài nhất (Substring)",
        title_en="Longest Palindromic Substring",
        topic_id="dp-lis-lcs", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "palindrome", "string"], statement=statement,
        vn_pattern="DP interval HOẶC expand-around-center.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Hai cách: (a) DP isPal[i][j] = palindrome? trans isPal[i+1][j-1] && S[i]==S[j]. Lặp theo L. O(N²) thời gian + bộ nhớ. (b) Expand-around-center: với mỗi tâm (i,i) và (i,i+1) mở rộng đối xứng, O(N) mỗi tâm. Tổng O(N²) thời gian, O(1) bộ nhớ thêm.",
        sketch="// for each center i: expand (l=i,r=i) and (l=i,r=i+1) while s[l]==s[r]",
    )


def build_dp_lcs_print():
    slug = "dp-lcs-print"

    def solve(inp: str) -> str:
        toks = inp.split("\n")
        a = toks[0].strip()
        b = toks[1].strip() if len(toks) > 1 else ""
        n, m = len(a), len(b)
        dp = [[0] * (m + 1) for _ in range(n + 1)]
        for i in range(1, n + 1):
            for j in range(1, m + 1):
                if a[i - 1] == b[j - 1]:
                    dp[i][j] = dp[i - 1][j - 1] + 1
                else:
                    dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])
        # reconstruct lexicographically: standard trace (prefer match)
        i, j = n, m
        out = []
        while i > 0 and j > 0:
            if a[i - 1] == b[j - 1]:
                out.append(a[i - 1])
                i -= 1; j -= 1
            elif dp[i - 1][j] >= dp[i][j - 1]:
                i -= 1
            else:
                j -= 1
        lcs = "".join(reversed(out))
        if not lcs:
            return f"{dp[n][m]}\n-"
        return f"{dp[n][m]}\n{lcs}"

    def gen(rng, n_lo, n_hi, alpha):
        a = "".join(rng.choice("abcdef"[:alpha]) for _ in range(rng.randint(n_lo, n_hi)))
        b = "".join(rng.choice("abcdef"[:alpha]) for _ in range(rng.randint(n_lo, n_hi)))
        return f"{a}\n{b}\n"

    def g1(rng): return gen(rng, 1, 8, 3)
    def g2(rng): return gen(rng, 30, 60, 4)
    def g3(rng): return gen(rng, 300, 500, 5)

    subtasks = [
        {"id": "st1", "title": "|A|,|B| ≤ 8", "points": 25, "constraint": "1 ≤ |A|, |B| ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "|A|,|B| ≤ 60", "points": 35, "constraint": "1 ≤ |A|, |B| ≤ 60", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|A|,|B| ≤ 500", "points": 40, "constraint": "1 ≤ |A|, |B| ≤ 500", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho 2 xâu `A`, `B`. Hãy in **độ dài** rồi **một dãy con chung dài nhất** (LCS) của 2 xâu. "
        "Nếu LCS rỗng, in `-`. (Nếu có nhiều LCS hợp lệ, in một dãy bất kỳ; chấm theo cách truy "
        "vết chuẩn ưu tiên match, sau đó ưu tiên đi lên.)\n\n"
        "**Input**: 2 dòng, mỗi dòng 1 xâu.\n\n"
        "**Output**: dòng 1 là độ dài; dòng 2 là LCS."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê dãy con A, check với B.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DP LCS chuẩn dp[i][j]; sau đó truy vết từ (n,m) về (0,0).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Truy vết: nếu A[i-1]=B[j-1] thì ghi vào kết quả, đi tới (i-1,j-1); ngược lại đi tới ô lớn hơn.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="LCS — In ra dãy con chung dài nhất",
        title_en="Print Longest Common Subsequence",
        topic_id="dp-lis-lcs", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "lcs", "reconstruction"], statement=statement,
        vn_pattern="DP LCS + truy vết.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Tính bảng dp[i][j] = LCS độ dài giữa A[:i] và B[:j] như chuẩn (O(NM)). Truy vết từ (n,m): nếu A[i-1]=B[j-1] thì thêm ký tự vào ans và (i,j)→(i-1,j-1); ngược lại đi sang (i-1,j) nếu dp[i-1][j]≥dp[i][j-1], ngược lại (i,j-1). Reverse ans.",
        sketch="// dp + trace from (n,m) preferring match then up",
    )


def build_dp_russian_doll():
    slug = "dp-russian-doll"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        items = []
        for i in range(n):
            w = int(toks[1 + 2 * i])
            h = int(toks[2 + 2 * i])
            items.append((w, h))
        # sort by w asc, for equal w sort by h desc (to ensure LIS won't pick same w)
        items.sort(key=lambda x: (x[0], -x[1]))
        # LIS on h
        from bisect import bisect_left
        tails = []
        for _, h in items:
            pos = bisect_left(tails, h)
            if pos == len(tails):
                tails.append(h)
            else:
                tails[pos] = h
        return str(len(tails))

    def gen(rng, n_lo, n_hi, v_hi):
        n = rng.randint(n_lo, n_hi)
        lines = [str(n)]
        for _ in range(n):
            lines.append(f"{rng.randint(1, v_hi)} {rng.randint(1, v_hi)}")
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 1, 8, 10)
    def g2(rng): return gen(rng, 50, 200, 1000)
    def g3(rng): return gen(rng, 5000, 10000, 100000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 200 (O(N²))", "points": 30, "constraint": "1 ≤ N ≤ 200", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^4 (O(N log N))", "points": 45, "constraint": "1 ≤ N ≤ 10^4", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho `N` phong bì, mỗi phong bì có chiều rộng `w` và chiều cao `h`. Phong bì X có thể "
        "lồng vào phong bì Y nếu `wX < wY` **và** `hX < hY`. Hãy tìm **số phong bì lớn nhất** "
        "trong một chuỗi lồng tăng dần.\n\n"
        "**Input**: dòng 1 chứa N; N dòng tiếp theo mỗi dòng 2 số `w h`.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Vét cạn N! hoán vị.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Sort theo (w, h) rồi LIS O(N²) trên h.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Sort theo w tăng, w bằng nhau sort h GIẢM dần để tránh trùng w trong LIS. Sau đó LIS O(N log N) trên h.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Lồng phong bì (Russian Doll Envelopes)",
        title_en="Russian Doll Envelopes",
        topic_id="dp-lis-lcs", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "lis", "sorting"], statement=statement,
        vn_pattern="2D LIS — sort 1 chiều rồi LIS chiều còn lại.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Sort các phong bì theo w tăng, w bằng nhau thì h GIẢM (để tránh chọn 2 phong bì cùng w, vốn không lồng được). Sau đó tìm LIS trên dãy h. O(N²) hoặc O(N log N) bằng patience sort.",
        sketch="// sort by (w asc, h desc); LIS(h) by patience sort",
    )


# ===========================================================================
# dp-grid
# ===========================================================================
def build_dp_tile_2xn():
    slug = "dp-tile-2xn"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        n = int(inp.strip())
        if n == 0:
            return "1"
        if n == 1:
            return "1"
        a, b = 1, 1
        for _ in range(2, n + 1):
            a, b = b, (a + b) % MOD
        return str(b)

    def gen(rng, n_hi):
        n = rng.randint(0, n_hi)
        return f"{n}\n"

    def g1(rng): return gen(rng, 8)
    def g2(rng): return gen(rng, 50)
    def g3(rng): return gen(rng, 10**6)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "0 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 50", "points": 30, "constraint": "0 ≤ N ≤ 50", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^6", "points": 45, "constraint": "0 ≤ N ≤ 10^6", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Đếm số cách lát bảng `2×N` bằng các miếng domino `1×2` (đặt ngang hoặc dọc). "
        "In modulo 10^9+7.\n\n"
        "**Input**: 1 số `N`.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Vẽ tay với N nhỏ và liệt kê.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Tách theo cột cuối: 1 dọc → f(n-1); 2 ngang → f(n-2). f(n)=f(n-1)+f(n-2).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Đây chính là Fibonacci. O(N) cộng dồn.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đếm cách lát domino bảng 2×N",
        title_en="Domino Tiling 2xN",
        topic_id="dp-grid", tier="T1",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=1,
        tags=["dp", "tiling", "fibonacci"], statement=statement,
        vn_pattern="Tiling cơ bản — quy về Fibonacci.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Gọi f(n) là số cách lát 2×N. Xét cột cuối: nếu đặt 1 miếng dọc → còn 2×(N-1); nếu đặt 2 miếng ngang ở 2 hàng cuối → còn 2×(N-2). Suy ra f(n)=f(n-1)+f(n-2), f(0)=f(1)=1. Cộng dồn modulo. O(N).",
        sketch="// a,b=1,1; loop n: a,b=b,(a+b)%MOD",
    )


def build_dp_tile_3xn():
    slug = "dp-tile-3xn"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        n = int(inp.strip())
        # tiling 3xN with 2x1 dominoes only (3xN domino tiling)
        # f(0)=1, f(odd)=0, f(2)=3, f(2k)=4*f(2k-2)-f(2k-4)
        if n % 2 == 1:
            return "0"
        if n == 0:
            return "1"
        if n == 2:
            return "3"
        # iter
        prev2 = 1  # f(0)
        prev = 3   # f(2)
        for k in range(4, n + 1, 2):
            cur = (4 * prev - prev2) % MOD
            prev2, prev = prev, cur
        return str(prev % MOD)

    def gen(rng, n_hi):
        # pick n even-biased so we have both 0 and >0 answers
        n = rng.randint(0, n_hi)
        return f"{n}\n"

    def g1(rng): return gen(rng, 8)
    def g2(rng): return gen(rng, 80)
    def g3(rng): return gen(rng, 10**6)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "0 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 80", "points": 30, "constraint": "0 ≤ N ≤ 80", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^6", "points": 45, "constraint": "0 ≤ N ≤ 10^6", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Đếm số cách lát bảng `3×N` bằng các miếng domino `1×2` (đặt ngang hoặc dọc). "
        "In modulo 10^9+7. (Khi N lẻ, kết quả = 0.)\n\n"
        "**Input**: 1 số `N`.\n\n"
        "**Output**: 1 số."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Liệt kê tay với N=2 (3 cách), N=4.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DP theo profile cột (bitmask 3 bit). O(N · 2^3 · 2^3).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Công thức truy hồi đẹp: f(2k)=4·f(2k-2)-f(2k-4), f(0)=1, f(2)=3, f(lẻ)=0.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đếm cách lát domino bảng 3×N",
        title_en="Domino Tiling 3xN",
        topic_id="dp-grid", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "tiling", "profile-dp"], statement=statement,
        vn_pattern="Profile DP hoặc công thức truy hồi đẹp.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Khi N lẻ: 0 (số ô = 3N lẻ → không lát được domino 1×2). Khi N=2k chẵn: công thức f(2k) = 4·f(2k-2) − f(2k-4) với f(0)=1, f(2)=3. Cộng dồn mod 10^9+7. O(N). Cách khác: profile DP với bitmask 3 bit, chuyển trạng thái giữa các cột.",
        sketch="// f(0)=1, f(2)=3, f(2k)=4*f(2k-2)-f(2k-4)",
    )


def build_dp_cherry_pickup():
    slug = "dp-cherry-pickup"

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        m = int(toks[idx]); idx += 1
        g = []
        for i in range(n):
            row = list(map(int, toks[idx:idx + m]))
            idx += m
            g.append(row)
        NEG = -10 ** 9
        # dp[k][i1][i2] = best after k moves; positions (i1, k-i1) and (i2, k-i2)
        dp = [[[NEG] * n for _ in range(n)] for __ in range(n + m - 1)]
        dp[0][0][0] = g[0][0]
        for k in range(1, n + m - 1):
            for i1 in range(max(0, k - (m - 1)), min(n - 1, k) + 1):
                j1 = k - i1
                if not (0 <= j1 < m):
                    continue
                for i2 in range(max(0, k - (m - 1)), min(n - 1, k) + 1):
                    j2 = k - i2
                    if not (0 <= j2 < m):
                        continue
                    best = NEG
                    for di1 in (0, -1):
                        pi1 = i1 + di1
                        for di2 in (0, -1):
                            pi2 = i2 + di2
                            if pi1 < 0 or pi2 < 0:
                                continue
                            v = dp[k - 1][pi1][pi2]
                            if v > best:
                                best = v
                    if best == NEG:
                        continue
                    if i1 == i2:
                        dp[k][i1][i2] = best + g[i1][j1]
                    else:
                        dp[k][i1][i2] = best + g[i1][j1] + g[i2][j2]
        ans = dp[n + m - 2][n - 1][n - 1]
        return str(max(ans, 0))

    def gen(rng, n_lo, n_hi, v_lo, v_hi):
        n = rng.randint(n_lo, n_hi)
        m = rng.randint(n_lo, n_hi)
        # ensure paths exist: keep cells non-negative most of the time
        lines = [f"{n} {m}"]
        for _ in range(n):
            lines.append(" ".join(str(rng.randint(v_lo, v_hi)) for _ in range(m)))
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 1, 4, 0, 5)
    def g2(rng): return gen(rng, 5, 15, 0, 9)
    def g3(rng): return gen(rng, 20, 40, 0, 9)

    subtasks = [
        {"id": "st1", "title": "N,M ≤ 4", "points": 25, "constraint": "1 ≤ N,M ≤ 4", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N,M ≤ 15", "points": 35, "constraint": "1 ≤ N,M ≤ 15", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N,M ≤ 40", "points": 40, "constraint": "1 ≤ N,M ≤ 40", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Có lưới `N×M` (N hàng, M cột), mỗi ô có số `g[i][j] ≥ 0` (anh đào). Hai robot đồng thời "
        "đi từ `(0,0)` đến `(N-1,M-1)`, mỗi bước đi phải, hoặc xuống. Nếu cả 2 đi qua cùng 1 ô, "
        "ô đó chỉ được tính 1 lần. Tìm **tổng anh đào lớn nhất** thu được.\n\n"
        "**Input**: dòng 1 chứa N M; N dòng tiếp theo, mỗi dòng M số.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Lưới nhỏ — vét cạn 2 đường đi.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "Đồng bộ 2 robot theo bước k → (i1, k-i1) và (i2, k-i2). DP 3D theo (k, i1, i2).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Mỗi trạng thái có 4 transition (2x2 lựa chọn đi trước). Khi i1=i2 chỉ cộng 1 ô.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="2 robot hái anh đào trên lưới",
        title_en="Cherry Pickup (2 robots)",
        topic_id="dp-grid", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["dp", "grid", "double-path"], statement=statement,
        vn_pattern="DP đồng bộ 2 con đường theo bước.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Cho 2 robot đồng bộ theo bước k = i+j. Trạng thái dp[k][i1][i2] với j1=k-i1, j2=k-i2. Trans từ (k-1, i1' ∈ {i1, i1-1}, i2' ∈ {i2, i2-1}). Khi i1=i2 và j1=j2 (cùng ô) chỉ cộng g[i1][j1] một lần, ngược lại cộng cả hai. O(N²(N+M)).",
        sketch="// dp[k][i1][i2]; 4 transitions; if same cell add once",
        time_limit_s=2,
    )


def build_dp_paths_king():
    slug = "dp-paths-king"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        m = int(toks[idx]); idx += 1
        g = []
        for i in range(n):
            row = list(toks[idx])
            idx += 1
            g.append(row)
        if g[0][0] == "#" or g[n - 1][m - 1] == "#":
            return "0"
        dp = [[0] * m for _ in range(n)]
        dp[0][0] = 1
        for i in range(n):
            for j in range(m):
                if g[i][j] == "#":
                    dp[i][j] = 0
                    continue
                if i == 0 and j == 0:
                    continue
                v = 0
                # king: 3 incoming directions (left, up, up-left)
                if i > 0:
                    v += dp[i - 1][j]
                if j > 0:
                    v += dp[i][j - 1]
                if i > 0 and j > 0:
                    v += dp[i - 1][j - 1]
                dp[i][j] = v % MOD
        return str(dp[n - 1][m - 1])

    def gen(rng, n_lo, n_hi, p_block):
        n = rng.randint(n_lo, n_hi)
        m = rng.randint(n_lo, n_hi)
        lines = [f"{n} {m}"]
        for _ in range(n):
            row = "".join(("#" if rng.random() < p_block else ".") for _ in range(m))
            lines.append(row)
        # clear start and end to avoid trivial 0
        rows = [list(r) for r in lines[1:]]
        rows[0][0] = "."
        rows[-1][-1] = "."
        return f"{n} {m}\n" + "\n".join("".join(r) for r in rows) + "\n"

    def g1(rng): return gen(rng, 1, 4, 0.2)
    def g2(rng): return gen(rng, 8, 20, 0.2)
    def g3(rng): return gen(rng, 80, 200, 0.15)

    subtasks = [
        {"id": "st1", "title": "N,M ≤ 4", "points": 25, "constraint": "1 ≤ N,M ≤ 4", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N,M ≤ 20", "points": 30, "constraint": "1 ≤ N,M ≤ 20", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N,M ≤ 200", "points": 45, "constraint": "1 ≤ N,M ≤ 200", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Lưới `N×M`, ô `.` đi được, ô `#` bị chặn. Quân vua xuất phát từ `(0,0)` đến `(N-1,M-1)` "
        "mỗi bước có thể đi **phải, xuống, hoặc chéo phải-xuống**. Đếm số đường đi (mod 10^9+7).\n\n"
        "**Input**: dòng 1 chứa N M; N dòng tiếp theo, mỗi dòng 1 xâu M ký tự.\n\n"
        "**Output**: 1 số."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Quy nạp/đệ quy có nhớ trên ô.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "dp[i][j] = dp[i-1][j] + dp[i][j-1] + dp[i-1][j-1] nếu ô đi được.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Modulo trên từng phép cộng. O(NM).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đếm đường đi quân vua trên lưới có chướng ngại",
        title_en="King Paths on Grid",
        topic_id="dp-grid", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["dp", "grid", "counting"], statement=statement,
        vn_pattern="Grid DP 3 hướng vào (trái, trên, chéo).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[i][j] = số cách đến (i,j). Nếu g[i][j]='#' → 0. Còn lại dp[i][j] = dp[i-1][j] + dp[i][j-1] + dp[i-1][j-1] (các chỉ số hợp lệ). dp[0][0]=1 nếu không bị chặn. O(NM).",
        sketch="// dp[i][j] = dp[i-1][j] + dp[i][j-1] + dp[i-1][j-1] mod",
    )


# ===========================================================================
# tree-dp-intro
# ===========================================================================
def build_tdp_knapsack():
    slug = "tdp-knapsack"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        m = int(toks[idx]); idx += 1
        h = list(map(int, toks[idx:idx + n])); idx += n
        s = list(map(int, toks[idx:idx + n])); idx += n
        parent = [0] * (n + 1)
        children = [[] for _ in range(n + 1)]
        for i in range(1, n):
            parent[i + 1] = int(toks[idx]); idx += 1
            children[parent[i + 1]].append(i + 1)
        # Root is 1; we treat virtual root 0 children = [1] so we pick at most m courses total
        children[0].append(1)
        # f[v][k] = max stars picking exactly k courses in subtree(v), MUST take v if v != 0
        INF = -1
        def dfs(v):
            if v == 0:
                # virtual root: no cost itself
                f = [0] + [INF] * m
            else:
                if h[v - 1] > m:
                    return [0] + [INF] * m
                f = [INF] * (m + 1)
                f[0] = 0  # don't take v's subtree at all
                f[h[v - 1]] = s[v - 1]  # take v alone
            for c in children[v]:
                fc = dfs(c)
                new_f = [INF] * (m + 1)
                for k in range(m + 1):
                    if f[k] == INF:
                        continue
                    for kk in range(m - k + 1):
                        if fc[kk] == INF:
                            continue
                        cand = f[k] + fc[kk]
                        if cand > new_f[k + kk]:
                            new_f[k + kk] = cand
                f = new_f
            return f

        # avoid Python recursion-limit on deeper trees: do iterative DFS using post-order
        # but with n ≤ a couple hundred recursion is fine.
        sys.setrecursionlimit(10000)
        f = dfs(0)
        ans = max(x for x in f if x != INF)
        return str(ans)

    def gen(rng, n_hi, m_hi):
        n = rng.randint(1, n_hi)
        m = rng.randint(1, n)
        h_list = [rng.randint(1, max(1, n // 2)) for _ in range(n)]
        s_list = [rng.randint(0, 20) for _ in range(n)]
        parents = []
        for i in range(2, n + 1):
            parents.append(rng.randint(1, i - 1))
        lines = [f"{n} {m}", " ".join(map(str, h_list)), " ".join(map(str, s_list))]
        if parents:
            lines.append(" ".join(map(str, parents)))
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 6, 6)
    def g2(rng): return gen(rng, 40, 40)
    def g3(rng): return gen(rng, 150, 150)

    subtasks = [
        {"id": "st1", "title": "N ≤ 6", "points": 25, "constraint": "1 ≤ N ≤ 6", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 40", "points": 35, "constraint": "1 ≤ N ≤ 40", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 150", "points": 40, "constraint": "1 ≤ N ≤ 150", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Trường có `N` khoá học (đánh số 1..N), khoá 1 là gốc. Mỗi khoá `i` cần `h[i]` "
        "đơn vị tín chỉ và cho `s[i]` điểm. Khoá `i` (i>1) là **tiên quyết** "
        "của khoá `p[i]` (cha trong cây). Bạn có ngân sách tổng cộng `M` tín chỉ. "
        "Hãy chọn tập khoá để học sao cho tổng tín chỉ ≤ M và tổng điểm lớn nhất; "
        "lưu ý nếu học khoá `i` thì phải học mọi tổ tiên của nó.\n\n"
        "**Input**: dòng 1 chứa N M; dòng 2 chứa h[1..N]; dòng 3 chứa s[1..N]; "
        "dòng 4 chứa p[2..N] (cha của các khoá 2..N).\n\n"
        "**Output**: 1 số nguyên (điểm tối đa)."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Thử mọi tập con và kiểm tra điều kiện tổ tiên.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DP trên cây: f[v][k] = điểm tối đa khi cây con v dùng đúng k tín chỉ.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Khi gộp con vào cha, dùng knapsack tổ hợp. Tổng phép O(N·M) nhờ trick subtree-size.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Cây khoá học — Tree Knapsack",
        title_en="Tree Knapsack (Courses with Prerequisites)",
        topic_id="tree-dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["tree-dp", "knapsack", "prerequisites"], statement=statement,
        vn_pattern="Tree DP + knapsack gộp con vào cha.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Cấp gốc ảo 0 → 1. f[v][k] = điểm tối đa khi cây con v dùng đúng k tín chỉ (nếu v thật, phải lấy v hoặc bỏ cả cây con v). Gộp từng con bằng knapsack: new_f[k+kk] = max(new_f[k+kk], f[k]+f_child[kk]). Bỏ cây con: f[0]=0. Đáp án max(f[root][k]) với k≤M. Độ phức tạp O(N·M).",
        sketch="// dfs(v): f[0]=0; if v!=virtual: f[h[v]]=s[v]; merge children via knapsack",
        time_limit_s=2,
    )


def build_tdp_min_vcover():
    slug = "tdp-min-vcover"

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        adj = [[] for _ in range(n + 1)]
        for _ in range(n - 1):
            u = int(toks[idx]); idx += 1
            v = int(toks[idx]); idx += 1
            adj[u].append(v)
            adj[v].append(u)
        # iterative DFS rooted at 1
        # dp[v][0] = min VC subtree v without taking v
        # dp[v][1] = min VC subtree v taking v
        order = []
        parent = [0] * (n + 1)
        stack = [1]
        seen = [False] * (n + 1)
        seen[1] = True
        while stack:
            u = stack.pop()
            order.append(u)
            for w in adj[u]:
                if not seen[w]:
                    seen[w] = True
                    parent[w] = u
                    stack.append(w)
        dp0 = [0] * (n + 1)
        dp1 = [1] * (n + 1)
        for u in reversed(order):
            for w in adj[u]:
                if parent[w] == u:
                    dp0[u] += dp1[w]            # must take child
                    dp1[u] += min(dp0[w], dp1[w])
        return str(min(dp0[1], dp1[1]))

    def gen(rng, n_hi):
        n = rng.randint(1, n_hi)
        lines = [str(n)]
        for i in range(2, n + 1):
            p = rng.randint(1, i - 1)
            lines.append(f"{p} {i}")
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 8)
    def g2(rng): return gen(rng, 100)
    def g3(rng): return gen(rng, 5000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 30, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 5000", "points": 45, "constraint": "1 ≤ N ≤ 5000", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho cây vô hướng `N` đỉnh (đánh số 1..N), N-1 cạnh. Hãy tìm **lực lượng tập phủ đỉnh tối "
        "thiểu** (Minimum Vertex Cover): tập đỉnh nhỏ nhất sao cho mỗi cạnh có ít nhất một đầu "
        "thuộc tập.\n\n"
        "**Input**: dòng 1 chứa N; N-1 dòng tiếp theo, mỗi dòng 2 số u v là cạnh.\n\n"
        "**Output**: 1 số nguyên."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Thử mọi tập con đỉnh, kiểm tra phủ.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DP cây: dp[v][0/1] = MVC trong cây con v khi không lấy/có lấy v.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "dp[v][0]=Σdp[c][1]; dp[v][1]=1+Σmin(dp[c][0],dp[c][1]).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Tập phủ đỉnh nhỏ nhất trên cây",
        title_en="Min Vertex Cover (Tree)",
        topic_id="tree-dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["tree-dp", "vertex-cover"], statement=statement,
        vn_pattern="Tree DP cổ điển — trạng thái (cha có lấy / không lấy).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="dp[v][0] = MVC trong cây con v khi KHÔNG lấy v (thì mọi con phải lấy: dp[v][0] = Σ dp[c][1]). dp[v][1] = MVC khi LẤY v (con có thể lấy hoặc không: dp[v][1] = 1 + Σ min(dp[c][0], dp[c][1])). Đáp án min(dp[root][0], dp[root][1]). O(N).",
        sketch="// dp[v][0]=sum dp[c][1]; dp[v][1]=1+sum min(dp[c][0],dp[c][1])",
    )


def build_tdp_paths_sum():
    slug = "tdp-paths-sum"

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        adj = [[] for _ in range(n + 1)]
        for _ in range(n - 1):
            u = int(toks[idx]); idx += 1
            v = int(toks[idx]); idx += 1
            w = int(toks[idx]); idx += 1
            adj[u].append((v, w))
            adj[v].append((u, w))
        order = []
        parent = [0] * (n + 1)
        parent_w = [0] * (n + 1)
        seen = [False] * (n + 1)
        stack = [1]
        seen[1] = True
        while stack:
            u = stack.pop()
            order.append(u)
            for v, w in adj[u]:
                if not seen[v]:
                    seen[v] = True
                    parent[v] = u
                    parent_w[v] = w
                    stack.append(v)
        size = [1] * (n + 1)
        for u in reversed(order):
            if parent[u]:
                size[parent[u]] += size[u]
        total = 0
        for v in range(2, n + 1):
            total += size[v] * (n - size[v]) * parent_w[v]
        return str(total)

    def gen(rng, n_lo, n_hi, w_hi):
        n = rng.randint(n_lo, n_hi)
        lines = [str(n)]
        for i in range(2, n + 1):
            p = rng.randint(1, i - 1)
            w = rng.randint(1, w_hi)
            lines.append(f"{p} {i} {w}")
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 2, 8, 5)
    def g2(rng): return gen(rng, 50, 200, 100)
    def g3(rng): return gen(rng, 5000, 20000, 1000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "2 ≤ N ≤ 8", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 200", "points": 30, "constraint": "2 ≤ N ≤ 200", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 2·10^4", "points": 45, "constraint": "2 ≤ N ≤ 2·10^4", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho cây có trọng số `N` đỉnh, `N-1` cạnh trọng số dương. Tính **tổng khoảng cách** giữa "
        "tất cả các cặp đỉnh `(u, v)` với `u < v`.\n\n"
        "**Input**: dòng 1 chứa N; N-1 dòng tiếp theo, mỗi dòng 3 số `u v w` là cạnh trọng số.\n\n"
        "**Output**: 1 số nguyên duy nhất."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "BFS/DFS từ mỗi đỉnh tính khoảng cách tới mọi đỉnh.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "O(N²) bằng N lần BFS đủ AC.", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Cách O(N): mỗi cạnh có size[v] đỉnh ở một phía và N-size[v] ở phía kia → cạnh đó nhân (size·(N-size)·w).", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Tổng khoảng cách mọi cặp đỉnh trên cây",
        title_en="Sum of All Pairwise Distances on Tree",
        topic_id="tree-dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["tree-dp", "size-trick"], statement=statement,
        vn_pattern="Trick mỗi cạnh đóng góp size·(N-size)·w.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Với mỗi cạnh nối cha-con với trọng số w, gọi size[v] là kích thước cây con phía con. Cạnh đó nằm trên mọi đường đi giữa 1 đỉnh trong size[v] và 1 đỉnh ngoài, tức size[v]·(N-size[v]) đường. Tổng = Σ size[v] · (N-size[v]) · w. Tính size bằng 1 lần DFS. O(N).",
        sketch="// size by post-order; ans = sum size[v]*(N-size[v])*w[v]",
    )


def build_tdp_color_tree():
    slug = "tdp-color-tree"
    MOD = 1_000_000_007

    def solve(inp: str) -> str:
        toks = inp.split()
        idx = 0
        n = int(toks[idx]); idx += 1
        k = int(toks[idx]); idx += 1
        adj = [[] for _ in range(n + 1)]
        for _ in range(n - 1):
            u = int(toks[idx]); idx += 1
            v = int(toks[idx]); idx += 1
            adj[u].append(v)
            adj[v].append(u)
        # number of proper colorings of a tree with K colors = K * (K-1)^(N-1)
        if n == 1:
            return str(k % MOD)
        ans = k * pow(k - 1, n - 1, MOD) % MOD
        return str(ans)

    def gen(rng, n_hi, k_hi):
        n = rng.randint(1, n_hi)
        k = rng.randint(2, k_hi)
        lines = [f"{n} {k}"]
        for i in range(2, n + 1):
            p = rng.randint(1, i - 1)
            lines.append(f"{p} {i}")
        return "\n".join(lines) + "\n"

    def g1(rng): return gen(rng, 6, 4)
    def g2(rng): return gen(rng, 30, 20)
    def g3(rng): return gen(rng, 10**5, 10**6)

    subtasks = [
        {"id": "st1", "title": "N ≤ 6, K ≤ 4", "points": 25, "constraint": "1 ≤ N ≤ 6; 2 ≤ K ≤ 4", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "N ≤ 30, K ≤ 20", "points": 30, "constraint": "1 ≤ N ≤ 30; 2 ≤ K ≤ 20", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^5", "points": 45, "constraint": "1 ≤ N ≤ 10^5; 2 ≤ K ≤ 10^6", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    strip_gen(subtasks)
    statement = (
        "Cho cây `N` đỉnh, `N-1` cạnh và `K` màu. Đếm số cách tô màu cây sao cho hai đỉnh kề nhau "
        "luôn khác màu (mod 10^9+7).\n\n"
        "**Input**: dòng 1 chứa N K; N-1 dòng tiếp theo mỗi dòng 2 số u v.\n\n"
        "**Output**: 1 số."
    )
    hints = [
        {"id": f"{slug}-h1", "subtaskId": "st1", "content": "Thử mọi bảng màu K^N, lọc hợp lệ.", "starCost": 0},
        {"id": f"{slug}-h2", "subtaskId": "st2", "content": "DFS từ gốc: gốc có K cách, mỗi đỉnh con có K-1 cách (khác cha).", "starCost": 1},
        {"id": f"{slug}-h3", "subtaskId": "st3", "content": "Công thức gọn: K · (K-1)^(N-1). Dùng lũy thừa nhanh + modulo.", "starCost": 1},
    ]
    return base_problem(
        slug=slug, title="Đếm cách tô màu cây K màu",
        title_en="Count Proper Tree Colorings",
        topic_id="tree-dp-intro", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["tree-dp", "counting", "fast-power"], statement=statement,
        vn_pattern="Tree DP tiến hoá thành công thức K·(K-1)^(N-1).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Vì cây không có chu trình, DFS từ gốc: gốc K cách. Mỗi đỉnh con khác màu cha → (K-1) cách. Có N-1 cạnh, nên đáp án = K · (K-1)^(N-1) mod 10^9+7. Dùng lũy thừa nhanh. O(N + log N).",
        sketch="// ans = k * pow(k-1, n-1, MOD)",
    )


# ===========================================================================
# Topic → list of (slug, title, tier, skills) to APPEND to existing roadmap.
# We APPEND (preserve existing 5), not replace.
# ===========================================================================
NEW_BY_TOPIC = {
    "dp-intro": [
        ("dp-min-jumps",       "Số bước nhảy tối thiểu",                    "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-decode-ways",     "Đếm số cách giải mã (A-Z)",                 "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-paint-fence",     "Sơn hàng rào K màu",                        "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-max-prod-subarr", "Tích lớn nhất của dãy con liên tiếp",       "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "dp-knapsack": [
        ("dp-rod-cut",         "Cắt thanh sắt tối ưu",                      "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-egg-drop",        "Bài toán thả trứng",                        "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-knap-bounded",    "Túi có giới hạn số bản sao",                "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-target-sum",      "Đặt dấu +/− đạt tổng đích",                 "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "dp-lis-lcs": [
        ("dp-lps",             "Dãy con palindrome dài nhất",               "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-lps-substring",   "Xâu con palindrome dài nhất",               "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-lcs-print",       "LCS — in dãy con chung",                    "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-russian-doll",    "Lồng phong bì (Russian Doll)",              "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "dp-grid": [
        ("dp-tile-2xn",        "Lát domino bảng 2×N",                       "T1", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-tile-3xn",        "Lát domino bảng 3×N",                       "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-cherry-pickup",   "2 robot hái anh đào",                       "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("dp-paths-king",      "Đếm đường đi quân vua",                     "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "tree-dp-intro": [
        ("tdp-knapsack",       "Cây khoá học — Tree Knapsack",              "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("tdp-min-vcover",     "Tập phủ đỉnh nhỏ nhất trên cây",            "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("tdp-paths-sum",      "Tổng khoảng cách mọi cặp đỉnh",             "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("tdp-color-tree",     "Đếm cách tô màu cây",                       "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
}

PROBLEM_TAGS = {
    "dp-min-jumps":       ["dp"],
    "dp-decode-ways":     ["dp", "counting"],
    "dp-paint-fence":     ["dp", "counting"],
    "dp-max-prod-subarr": ["dp", "kadane"],
    "dp-rod-cut":         ["dp", "knapsack"],
    "dp-egg-drop":        ["dp", "minimax"],
    "dp-knap-bounded":    ["dp", "knapsack"],
    "dp-target-sum":      ["dp", "knapsack", "counting"],
    "dp-lps":             ["dp", "interval-dp", "palindrome"],
    "dp-lps-substring":   ["dp", "palindrome", "string"],
    "dp-lcs-print":       ["dp", "lcs"],
    "dp-russian-doll":    ["dp", "lis"],
    "dp-tile-2xn":        ["dp", "tiling"],
    "dp-tile-3xn":        ["dp", "tiling"],
    "dp-cherry-pickup":   ["dp", "grid"],
    "dp-paths-king":      ["dp", "grid", "counting"],
    "tdp-knapsack":       ["tree-dp", "knapsack"],
    "tdp-min-vcover":     ["tree-dp"],
    "tdp-paths-sum":      ["tree-dp"],
    "tdp-color-tree":     ["tree-dp", "counting"],
}


def patch_roadmap() -> None:
    """Append (slug+metadata) into roadmap.json node.problems[] (preserving existing)."""
    data = json.loads(ROADMAP.read_text(encoding="utf-8"))
    touched = 0
    for node in data["nodes"]:
        topic = node["id"]
        if topic not in NEW_BY_TOPIC:
            continue
        # Preserve existing problem entries as-is. Existing are dicts on disk.
        existing_slugs = set()
        for p in node.get("problems", []):
            slug = p["slug"] if isinstance(p, dict) else p
            existing_slugs.add(slug)
        added = 0
        for (slug, title, tier, skills) in NEW_BY_TOPIC[topic]:
            if slug in existing_slugs:
                continue
            node["problems"].append({
                "slug": slug,
                "title": title,
                "tier": tier,
                "skills": skills,
                "difficulty": "intermediate",
                "maxStars": 3,
                "tags": PROBLEM_TAGS.get(slug, ["dp"]),
            })
            added += 1
        if added:
            touched += 1
            print(f"[roadmap] {topic}: +{added} problems")
    ROADMAP.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[roadmap] patched {touched} nodes")


def rebuild_index() -> None:
    slugs = sorted(p.stem for p in PROBLEMS_DIR.glob("*.json") if p.name != "index.json")
    INDEX.write_text(
        json.dumps(slugs, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[index] wrote {len(slugs)} slugs to {INDEX.relative_to(ROOT)}")


def main() -> None:
    if not PROBLEMS_DIR.exists():
        print(f"ERROR: {PROBLEMS_DIR} not found", file=sys.stderr)
        sys.exit(1)

    builders = [
        # dp-intro
        build_dp_min_jumps,
        build_dp_decode_ways,
        build_dp_paint_fence,
        build_dp_max_prod_subarr,
        # dp-knapsack
        build_dp_rod_cut,
        build_dp_egg_drop,
        build_dp_knap_bounded,
        build_dp_target_sum,
        # dp-lis-lcs
        build_dp_lps,
        build_dp_lps_substring,
        build_dp_lcs_print,
        build_dp_russian_doll,
        # dp-grid
        build_dp_tile_2xn,
        build_dp_tile_3xn,
        build_dp_cherry_pickup,
        build_dp_paths_king,
        # tree-dp-intro
        build_tdp_knapsack,
        build_tdp_min_vcover,
        build_tdp_paths_sum,
        build_tdp_color_tree,
    ]
    for fn in builders:
        prob = fn()
        write_problem(prob)
        n_cases = len(prob["testCases"])
        n_subs = len(prob["subtasks"])
        print(f"[ok] {prob['slug']:24s}  subtasks={n_subs} testCases={n_cases}")

    patch_roadmap()
    rebuild_index()
    print("done.")


if __name__ == "__main__":
    main()
