#!/usr/bin/env python3
"""
Phase 2 — generate 15 internal problems for the 3 empty roadmap nodes:
  - sieve-factorization (Day 27): 5 problems
  - string-hash         (Day 28): 5 problems
  - tree-dp-intro       (Day 29): 5 problems

Each problem has:
  - statement (Vietnamese)
  - 3-4 subtasks with increasing N
  - ~20 test cases generated by deterministic random + brute solver
  - hints per subtask
  - editorial + solutionSketch

Run:  python3 scripts/build_phase2_problems.py
Writes JSON files into public/data/problems/ and updates roadmap.json + index.json.
"""
import json
import random
import sys
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = ROOT / "public" / "data" / "problems"
ROADMAP = ROOT / "public" / "data" / "roadmap.json"
INDEX = PROBLEMS_DIR / "index.json"

CREATED_AT = "2026-05-25"


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------
def write_problem(problem: dict):
    """Validate basic invariants, then dump to public/data/problems/<slug>.json."""
    slug = problem["slug"]
    # Sanity: every testCase points to a real subtaskId, sub points add up.
    subtask_ids = {st["id"] for st in problem["subtasks"]}
    for tc in problem["testCases"]:
        assert tc["subtaskId"] in subtask_ids, f"{slug}: tc {tc['id']} has unknown sub {tc['subtaskId']}"
    pts = sum(st["points"] for st in problem["subtasks"])
    assert pts == 100, f"{slug}: subtask points sum to {pts}, expected 100"
    out = PROBLEMS_DIR / f"{slug}.json"
    out.write_text(json.dumps(problem, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def base_problem(
    slug: str,
    title: str,
    title_en: str,
    topic_id: str,
    tier: str,
    skills: list,
    difficulty: int,
    tags: list,
    statement: str,
    vn_pattern: str,
    subtasks: list,
    samples: list,
    test_cases: list,
    hints: list,
    editorial: str,
    sketch: str,
    time_limit_s: int = 1,
    memory_mb: int = 256,
) -> dict:
    return {
        "slug": slug,
        "title": title,
        "titleEn": title_en,
        "module": "roadmap",
        "topicId": topic_id,
        "tier": tier,
        "skills": skills,
        "difficulty": difficulty,
        "maxStars": 3,
        "tags": tags,
        "source": "Bài tự build (Phase 2)",
        "isExternal": False,
        "statement": statement,
        "vnPattern": vn_pattern,
        "fileIO": {"inputFile": "stdin", "outputFile": "stdout"},
        "subtasks": subtasks,
        "samples": samples,
        "testCases": test_cases,
        "hints": hints,
        "editorial": editorial,
        "solutionSketch": sketch,
        "timeLimit": time_limit_s,
        "memoryLimit": memory_mb,
        "timeLimitMs": time_limit_s * 1000,
        "memoryLimitKB": memory_mb * 1024,
        "createdAt": CREATED_AT,
    }


def generate_cases(slug: str, subtasks: list, solver: Callable[[str], str]) -> tuple:
    """For each subtask, generate ~5 test inputs by calling subtask['gen'](rng).
    Returns (test_cases, samples) where samples = first 2 cases from sub1.
    """
    rng = random.Random(hash(slug) & 0xFFFFFFFF)
    cases = []
    samples = []
    tc_id = 0
    for st in subtasks:
        for k in range(st["nCases"]):
            tc_id += 1
            inp = st["gen"](rng)
            out = solver(inp)
            cases.append({
                "id": f"tc{tc_id:02d}",
                "subtaskId": st["id"],
                "input": inp,
                "output": out,
            })
            if st["id"] == subtasks[0]["id"] and len(samples) < 2:
                samples.append({
                    "id": f"sample{len(samples) + 1}",
                    "input": inp,
                    "output": out,
                })
    return cases, samples


# ---------------------------------------------------------------------------
# sf-prime-table: đếm số nguyên tố trong [L, R]
# ---------------------------------------------------------------------------
def build_sf_prime_table():
    slug = "sf-prime-table"
    MAX = 200_000

    def solve(inp: str) -> str:
        toks = inp.split()
        q = int(toks[0])
        out = []
        for i in range(q):
            l = int(toks[1 + 2 * i])
            r = int(toks[2 + 2 * i])
            # naive: trial division for each n in [l, r]
            cnt = 0
            for n in range(l, r + 1):
                if n < 2:
                    continue
                ok = True
                d = 2
                while d * d <= n:
                    if n % d == 0:
                        ok = False
                        break
                    d += 1
                if ok:
                    cnt += 1
            out.append(str(cnt))
        return "\n".join(out)

    def g1(rng):
        # sub1: small numbers, R ≤ 100
        q = rng.randint(1, 5)
        lines = [str(q)]
        for _ in range(q):
            l = rng.randint(1, 50)
            r = rng.randint(l, l + 50)
            lines.append(f"{l} {r}")
        return "\n".join(lines) + "\n"

    def g2(rng):
        # sub2: medium, R ≤ 5000
        q = rng.randint(2, 8)
        lines = [str(q)]
        for _ in range(q):
            l = rng.randint(1, 4000)
            r = rng.randint(l, min(l + 2000, 5000))
            lines.append(f"{l} {r}")
        return "\n".join(lines) + "\n"

    def g3(rng):
        # sub3: large, R ≤ 200000 (sieve needed for full marks)
        q = rng.randint(1, 5)
        lines = [str(q)]
        for _ in range(q):
            l = rng.randint(1, MAX - 100)
            r = rng.randint(l, min(l + 200, MAX))
            lines.append(f"{l} {r}")
        return "\n".join(lines) + "\n"

    subtasks = [
        {"id": "st1", "title": "1 ≤ R ≤ 100, Q ≤ 5", "points": 30, "constraint": "1 ≤ L ≤ R ≤ 100; Q ≤ 5", "nCases": 6, "gen": g1},
        {"id": "st2", "title": "1 ≤ R ≤ 5000, Q ≤ 10", "points": 30, "constraint": "1 ≤ L ≤ R ≤ 5000; Q ≤ 10", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "1 ≤ R ≤ 2·10^5, Q ≤ 10 (cần sàng)", "points": 40, "constraint": "1 ≤ L ≤ R ≤ 2·10^5; Q ≤ 10", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]
        del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Trial division O(√n) cho mỗi n trong [L, R].", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Sàng Eratosthenes lên 5000, sau đó count với prefix sum.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Sàng tới 2·10^5 + prefix `isPrime[]` → mỗi query O(1).", "starCost": 1},
    ]
    statement = (
        "Cho Q truy vấn, mỗi truy vấn là một cặp `(L, R)`. Với mỗi truy vấn, hãy đếm số "
        "số nguyên tố trong đoạn `[L, R]`.\n\n"
        "**Input**: dòng 1 chứa Q; Q dòng tiếp theo, mỗi dòng 2 số L, R.\n\n"
        "**Output**: Q dòng, mỗi dòng 1 số nguyên là đáp án.\n\n"
        "**Ràng buộc**: 1 ≤ L ≤ R ≤ 2·10^5, 1 ≤ Q ≤ 10."
    )
    return base_problem(
        slug=slug, title="Đếm số nguyên tố trong [L, R]", title_en="Count Primes in Range",
        topic_id="sieve-factorization", tier="T2",
        skills=["S4-Cài đặt", "S2-Phân tích"], difficulty=2,
        tags=["sieve", "number-theory"], statement=statement,
        vn_pattern="Sàng Eratosthenes + prefix sum.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Tiền xử lý sàng `isPrime[]` rồi prefix `cnt[i] = số nguyên tố ≤ i`. Mỗi query trả `cnt[r] - cnt[l-1]`. O((MAX + Q) log log MAX).",
        sketch="// Sieve + prefix; answer = cnt[r] - cnt[l-1]",
    )


# ---------------------------------------------------------------------------
# sf-spf-factorize: phân tích N bằng SPF (smallest prime factor)
# ---------------------------------------------------------------------------
def build_sf_spf_factorize():
    slug = "sf-spf-factorize"

    def solve(inp: str) -> str:
        toks = inp.split()
        q = int(toks[0])
        out = []
        for i in range(q):
            n = int(toks[1 + i])
            facs = []
            d = 2
            while d * d <= n:
                if n % d == 0:
                    e = 0
                    while n % d == 0:
                        n //= d
                        e += 1
                    facs.append(f"{d}^{e}")
                d += 1
            if n > 1:
                facs.append(f"{n}^1")
            out.append(" ".join(facs) if facs else "1")
        return "\n".join(out)

    def g1(rng):
        q = rng.randint(2, 5)
        lines = [str(q)]
        for _ in range(q):
            lines.append(str(rng.randint(2, 100)))
        return "\n".join(lines) + "\n"

    def g2(rng):
        q = rng.randint(2, 8)
        lines = [str(q)]
        for _ in range(q):
            lines.append(str(rng.randint(2, 100000)))
        return "\n".join(lines) + "\n"

    def g3(rng):
        q = rng.randint(2, 10)
        lines = [str(q)]
        for _ in range(q):
            lines.append(str(rng.randint(2, 10_000_000)))
        return "\n".join(lines) + "\n"

    subtasks = [
        {"id": "st1", "title": "N ≤ 100", "points": 20, "constraint": "1 ≤ N ≤ 100; Q ≤ 5", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 10^5", "points": 35, "constraint": "1 ≤ N ≤ 10^5; Q ≤ 10", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 10^7 (cần SPF)", "points": 45, "constraint": "1 ≤ N ≤ 10^7; Q ≤ 10", "nCases": 8, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]
        del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Trial division O(√n) đủ AC.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Vẫn trial division O(√n), N ≤ 10^5 nên √N ≤ 316.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Sàng SPF[10^7+5]. Phân tích bằng vòng while `n /= spf[n]`. O(log n).", "starCost": 1},
    ]
    statement = (
        "Cho Q truy vấn, mỗi truy vấn là một số nguyên N. Hãy in ra phân tích thừa số "
        "nguyên tố của N dưới dạng `p1^e1 p2^e2 ... pk^ek` (tăng dần theo p).\n\n"
        "**Input**: dòng 1 là Q; Q dòng tiếp theo, mỗi dòng 1 số N.\n\n"
        "**Output**: Q dòng. Nếu N = 1 thì in `1`.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 10^7, 1 ≤ Q ≤ 10."
    )
    return base_problem(
        slug=slug, title="Phân tích thừa số bằng SPF", title_en="Factorize via SPF",
        topic_id="sieve-factorization", tier="T2",
        skills=["S4-Cài đặt", "S2-Phân tích"], difficulty=2,
        tags=["sieve", "factorization"], statement=statement,
        vn_pattern="Sàng SPF rồi phân tích O(log N).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Sàng SPF: spf[i*p] = p khi i*p chưa có SPF (i từ 2 lên). Phân tích N bằng cách while N > 1: lấy p = spf[N], đếm số mũ rồi N /= p^e.",
        sketch="// SPF sieve in O(MAX); factor each N in O(log N)",
    )


# ---------------------------------------------------------------------------
# sf-divisor-sum: với mỗi a_i, in tổng các ước (sigma_1)
# ---------------------------------------------------------------------------
def build_sf_divisor_sum():
    slug = "sf-divisor-sum"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        a = [int(x) for x in toks[1:1 + n]]
        out = []
        for x in a:
            s = 0
            d = 1
            while d * d <= x:
                if x % d == 0:
                    s += d
                    if d != x // d:
                        s += x // d
                d += 1
            out.append(str(s))
        return " ".join(out)

    def g1(rng):
        n = rng.randint(3, 8)
        a = [rng.randint(1, 50) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, a))}\n"

    def g2(rng):
        n = rng.randint(20, 100)
        a = [rng.randint(1, 5000) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, a))}\n"

    def g3(rng):
        n = rng.randint(200, 1000)
        a = [rng.randint(1, 1_000_000) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, a))}\n"

    subtasks = [
        {"id": "st1", "title": "N ≤ 10, A_i ≤ 50", "points": 25, "constraint": "1 ≤ N ≤ 10; 1 ≤ A_i ≤ 50", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100, A_i ≤ 5000", "points": 35, "constraint": "1 ≤ N ≤ 100; 1 ≤ A_i ≤ 5000", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000, A_i ≤ 10^6", "points": 40, "constraint": "1 ≤ N ≤ 1000; 1 ≤ A_i ≤ 10^6", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]
        del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Cộng các ước d của x cho d = 1..x.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Cho d từ 1 → √x, nếu d | x cộng d và x/d (tránh trùng khi d² = x).", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Vẫn O(√A) cho mỗi số, tổng O(N√A) ≈ 10⁶ phép.", "starCost": 1},
    ]
    statement = (
        "Cho dãy `a_1, a_2, ..., a_N`. Với mỗi `a_i` hãy in `σ(a_i)` — tổng tất cả ước dương của `a_i`.\n\n"
        "**Input**: dòng 1 là N; dòng 2 chứa N số `a_i`.\n\n"
        "**Output**: 1 dòng gồm N số `σ(a_1) σ(a_2) ... σ(a_N)` cách nhau bởi dấu cách.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000, 1 ≤ a_i ≤ 10^6."
    )
    return base_problem(
        slug=slug, title="Tổng các ước (σ)", title_en="Sum of Divisors",
        topic_id="sieve-factorization", tier="T2",
        skills=["S4-Cài đặt"], difficulty=2,
        tags=["divisors", "number-theory"], statement=statement,
        vn_pattern="Đếm ước bằng vòng √x.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Cho từng a_i, cộng các cặp (d, x/d) khi d² ≤ x. O(N √max(A)).",
        sketch="// for d = 1..sqrt(x): if x % d == 0 add d (+x/d if d²!=x)",
    )


# ---------------------------------------------------------------------------
# sf-distinct-prime: đếm ω(n) — số ước nguyên tố khác nhau
# ---------------------------------------------------------------------------
def build_sf_distinct_prime():
    slug = "sf-distinct-prime"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        a = [int(x) for x in toks[1:1 + n]]
        out = []
        for x in a:
            cnt = 0
            d = 2
            y = x
            while d * d <= y:
                if y % d == 0:
                    cnt += 1
                    while y % d == 0:
                        y //= d
                d += 1
            if y > 1:
                cnt += 1
            out.append(str(cnt))
        return " ".join(out)

    def g1(rng):
        n = rng.randint(3, 8)
        return f"{n}\n{' '.join(str(rng.randint(1, 100)) for _ in range(n))}\n"

    def g2(rng):
        n = rng.randint(20, 100)
        return f"{n}\n{' '.join(str(rng.randint(1, 100000)) for _ in range(n))}\n"

    def g3(rng):
        n = rng.randint(200, 1000)
        return f"{n}\n{' '.join(str(rng.randint(1, 10_000_000)) for _ in range(n))}\n"

    subtasks = [
        {"id": "st1", "title": "N ≤ 10, A_i ≤ 100", "points": 25, "constraint": "1 ≤ N ≤ 10; 1 ≤ A_i ≤ 100", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100, A_i ≤ 10^5", "points": 35, "constraint": "1 ≤ N ≤ 100; 1 ≤ A_i ≤ 10^5", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000, A_i ≤ 10^7", "points": 40, "constraint": "1 ≤ N ≤ 1000; 1 ≤ A_i ≤ 10^7", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]
        del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Trial division đếm ước nguyên tố khác nhau.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Khi tìm thấy ước p, while x % p == 0: x /= p; sau đó tiếp tục.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Tổng O(N√max(A)) ≈ 3·10⁶ phép — vẫn ổn. Có thể tăng tốc bằng SPF.", "starCost": 1},
    ]
    statement = (
        "Với mỗi số `a_i` trong dãy, hãy đếm số ước nguyên tố **khác nhau** của nó (ω-function).\n\n"
        "Ví dụ: 12 = 2² · 3 → ω(12) = 2.\n\n"
        "**Input**: dòng 1 là N; dòng 2 chứa N số `a_i`.\n\n"
        "**Output**: 1 dòng N số `ω(a_1) ... ω(a_N)`.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000, 1 ≤ a_i ≤ 10^7."
    )
    return base_problem(
        slug=slug, title="Số ước nguyên tố khác nhau (ω)", title_en="Distinct Prime Factors",
        topic_id="sieve-factorization", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["sieve", "number-theory"], statement=statement,
        vn_pattern="Trial division giữ riêng prime đã đếm.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Trial division: cho mỗi d = 2..√x, nếu d | x đếm 1 lần rồi chia hết d khỏi x. Cuối cùng nếu x > 1 thì cộng thêm 1.",
        sketch="// for d=2..sqrt(x): if d|x: cnt++, while d|x: x/=d; if x>1: cnt++",
    )


# ---------------------------------------------------------------------------
# sf-euler-phi: tính φ(n) cho mỗi n trong dãy
# ---------------------------------------------------------------------------
def build_sf_euler_phi():
    slug = "sf-euler-phi"

    def solve(inp: str) -> str:
        toks = inp.split()
        n = int(toks[0])
        a = [int(x) for x in toks[1:1 + n]]
        out = []
        for x in a:
            r = x
            y = x
            d = 2
            while d * d <= y:
                if y % d == 0:
                    while y % d == 0:
                        y //= d
                    r -= r // d
                d += 1
            if y > 1:
                r -= r // y
            out.append(str(r))
        return " ".join(out)

    def g1(rng):
        n = rng.randint(3, 8)
        return f"{n}\n{' '.join(str(rng.randint(1, 50)) for _ in range(n))}\n"

    def g2(rng):
        n = rng.randint(20, 100)
        return f"{n}\n{' '.join(str(rng.randint(1, 100000)) for _ in range(n))}\n"

    def g3(rng):
        n = rng.randint(200, 1000)
        return f"{n}\n{' '.join(str(rng.randint(1, 10_000_000)) for _ in range(n))}\n"

    subtasks = [
        {"id": "st1", "title": "N ≤ 10, A_i ≤ 50", "points": 25, "constraint": "1 ≤ N ≤ 10; 1 ≤ A_i ≤ 50", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100, A_i ≤ 10^5", "points": 35, "constraint": "1 ≤ N ≤ 100; 1 ≤ A_i ≤ 10^5", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000, A_i ≤ 10^7", "points": 40, "constraint": "1 ≤ N ≤ 1000; 1 ≤ A_i ≤ 10^7", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]
        del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Đếm số 1 ≤ k ≤ n có gcd(k, n) = 1.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Công thức Euler: φ(n) = n · ∏(1 - 1/p) cho mọi p | n.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Trial division O(√n) đủ. Có thể sieve φ lên 10^7 nếu cần nhiều query.", "starCost": 1},
    ]
    statement = (
        "Hàm Euler `φ(n)` = số nguyên k thoả 1 ≤ k ≤ n và gcd(k, n) = 1.\n\n"
        "Với mỗi `a_i`, in `φ(a_i)`.\n\n"
        "**Input**: dòng 1 là N; dòng 2 chứa N số `a_i`.\n\n"
        "**Output**: 1 dòng N số.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000, 1 ≤ a_i ≤ 10^7."
    )
    return base_problem(
        slug=slug, title="Hàm Euler φ(n)", title_en="Euler's Totient",
        topic_id="sieve-factorization", tier="T2",
        skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["totient", "number-theory"], statement=statement,
        vn_pattern="Công thức φ qua phân tích thừa số.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Với mỗi prime p | n: r = r - r/p (tương đương r *= (p-1)/p). Cuối cùng nếu còn 1 prime y > 1 thì r -= r/y.",
        sketch="// r = n; for p in primes_of(n): r -= r/p",
    )


# ---------------------------------------------------------------------------
# String hashing problems (sh-*) — topic = string-hash
# ---------------------------------------------------------------------------
def _rand_str(rng, n, alpha="ab"):
    return "".join(rng.choice(alpha) for _ in range(n))


def build_sh_pattern_count():
    slug = "sh-pattern-count"

    def solve(inp):
        lines = inp.strip("\n").split("\n")
        s, p = lines[0], lines[1]
        if not p or len(p) > len(s):
            return "0"
        c = 0
        for i in range(len(s) - len(p) + 1):
            if s[i:i + len(p)] == p:
                c += 1
        return str(c)

    def g1(rng):
        return f"{_rand_str(rng, rng.randint(5, 20))}\n{_rand_str(rng, rng.randint(1, 4))}\n"

    def g2(rng):
        return f"{_rand_str(rng, rng.randint(50, 500), 'abc')}\n{_rand_str(rng, rng.randint(1, 10), 'abc')}\n"

    def g3(rng):
        return f"{_rand_str(rng, rng.randint(2000, 5000), 'abcd')}\n{_rand_str(rng, rng.randint(1, 50), 'abcd')}\n"

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 20", "points": 25, "constraint": "1 ≤ |P| ≤ |S| ≤ 20", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 500", "points": 35, "constraint": "1 ≤ |S| ≤ 500", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 5·10^3 (hashing/KMP)", "points": 40, "constraint": "1 ≤ |S| ≤ 5·10^3", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "So sánh trực tiếp tại mỗi vị trí.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Vẫn O(N·M) đủ với N, M nhỏ.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Polynomial hash: tính `h(P)` 1 lần, trượt `h(S[i..i+M-1])` so trong O(1).", "starCost": 1},
    ]
    statement = (
        "Cho xâu S và mẫu P. Đếm số lần P xuất hiện trong S (cho phép overlap).\n\n"
        "**Input**: dòng 1 = S; dòng 2 = P.\n\n"
        "**Output**: 1 số nguyên.\n\n"
        "**Ràng buộc**: 1 ≤ |P| ≤ |S| ≤ 5·10^3."
    )
    return base_problem(
        slug=slug, title="Đếm số lần xuất hiện của mẫu", title_en="Count Pattern Occurrences",
        topic_id="string-hash", tier="T2", skills=["S4-Cài đặt", "S2-Phân tích"], difficulty=2,
        tags=["string-hash", "string"], statement=statement,
        vn_pattern="Polynomial hashing trượt cửa sổ.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Hash đa thức: h[i] = s[0]·b^(i-1) + ... + s[i-1]·b^0. Hash(S[l..r]) = h[r] - h[l-1]·b^(r-l+1). So sánh với hash(P).",
        sketch="// rolling hash; if h_S[i..i+m-1] == h_P then cnt++",
    )


def build_sh_distinct_len_k():
    slug = "sh-distinct-len-k"

    def solve(inp):
        lines = inp.strip("\n").split("\n")
        s = lines[0]
        k = int(lines[1])
        if k <= 0 or k > len(s):
            return "0"
        return str(len({s[i:i + k] for i in range(len(s) - k + 1)}))

    def g1(rng):
        n = rng.randint(5, 20)
        return f"{_rand_str(rng, n)}\n{rng.randint(1, min(4, n))}\n"

    def g2(rng):
        n = rng.randint(50, 500)
        return f"{_rand_str(rng, n, 'abc')}\n{rng.randint(2, min(20, n))}\n"

    def g3(rng):
        n = rng.randint(1500, 3000)
        return f"{_rand_str(rng, n, 'abcd')}\n{rng.randint(3, min(40, n))}\n"

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 20", "points": 25, "constraint": "1 ≤ |S| ≤ 20", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 500", "points": 35, "constraint": "1 ≤ |S| ≤ 500", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 3·10^3", "points": 40, "constraint": "1 ≤ |S| ≤ 3·10^3", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Đưa mọi substring vào set<string>.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Vẫn dùng set<string> với N ≤ 500.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Hash đa thức O(N) rồi cho từng hash vào unordered_set<long long>.", "starCost": 1},
    ]
    statement = (
        "Cho xâu S và số K. Đếm số xâu con **khác nhau** có độ dài đúng K.\n\n"
        "**Input**: dòng 1 = S; dòng 2 = K.\n\n"
        "**Output**: 1 số nguyên.\n\n"
        "**Ràng buộc**: 1 ≤ K ≤ |S| ≤ 3·10^3."
    )
    return base_problem(
        slug=slug, title="Số xâu con khác nhau độ dài K", title_en="Distinct Substrings of Length K",
        topic_id="string-hash", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["string-hash", "set"], statement=statement,
        vn_pattern="Hash từng cửa sổ rồi đếm distinct.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Tính hash O(N) cho mọi window độ dài K, đưa vào hash set, in size.",
        sketch="// rolling hash window of length K -> unordered_set<ull>",
    )


def build_sh_substring_eq():
    slug = "sh-substring-eq"

    def solve(inp):
        lines = inp.strip("\n").split("\n")
        s = lines[0]
        q = int(lines[1])
        out = []
        for i in range(q):
            l1, r1, l2, r2 = map(int, lines[2 + i].split())
            out.append("YES" if s[l1 - 1:r1] == s[l2 - 1:r2] else "NO")
        return "\n".join(out)

    def _gen_q(rng, s, q):
        n = len(s)
        lines = [s, str(q)]
        for _ in range(q):
            l1 = rng.randint(1, n)
            r1 = rng.randint(l1, n)
            ln = r1 - l1 + 1
            if rng.random() < 0.5 and ln <= n:
                l2 = rng.randint(1, n - ln + 1)
                r2 = l2 + ln - 1
            else:
                l2 = rng.randint(1, n)
                r2 = rng.randint(l2, n)
            lines.append(f"{l1} {r1} {l2} {r2}")
        return "\n".join(lines) + "\n"

    def g1(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(5, 20)), rng.randint(2, 8))

    def g2(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(50, 500), "abc"), rng.randint(10, 50))

    def g3(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(2000, 5000), "abcd"), rng.randint(50, 200))

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 20, Q ≤ 8", "points": 25, "constraint": "1 ≤ |S| ≤ 20; Q ≤ 8", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 500, Q ≤ 50", "points": 35, "constraint": "1 ≤ |S| ≤ 500; Q ≤ 50", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 5·10^3, Q ≤ 200", "points": 40, "constraint": "1 ≤ |S| ≤ 5·10^3; Q ≤ 200", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "So sánh trực tiếp 2 substring.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "O(|S|) mỗi query, đủ với |S| ≤ 500.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Hash prefix; mỗi query so 2 hash đoạn O(1) (precompute pow).", "starCost": 1},
    ]
    statement = (
        "Cho xâu S và Q truy vấn `(l1, r1, l2, r2)`. Với mỗi truy vấn, kiểm tra `S[l1..r1] == S[l2..r2]`.\n\n"
        "**Input**: dòng 1 = S; dòng 2 = Q; Q dòng tiếp theo, mỗi dòng 4 số (1-indexed).\n\n"
        "**Output**: Q dòng `YES` / `NO`.\n\n"
        "**Ràng buộc**: 1 ≤ |S| ≤ 5·10^3, 1 ≤ Q ≤ 200."
    )
    return base_problem(
        slug=slug, title="So khớp 2 đoạn xâu", title_en="Compare Two Substrings",
        topic_id="string-hash", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["string-hash"], statement=statement,
        vn_pattern="Hash 2 đoạn rồi so sánh O(1).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Tính h[i] và pw[i] = base^i mod p. Hash[l..r] = (h[r] - h[l-1]·pw[r-l+1]) mod p.",
        sketch="// precompute h, pw; compare h_sub(l1,r1) vs h_sub(l2,r2)",
    )


def build_sh_lcp_pair():
    slug = "sh-lcp-pair"

    def solve(inp):
        lines = inp.strip("\n").split("\n")
        s = lines[0]
        q = int(lines[1])
        out = []
        for k in range(q):
            i, j = map(int, lines[2 + k].split())
            i -= 1; j -= 1
            t = 0
            while i + t < len(s) and j + t < len(s) and s[i + t] == s[j + t]:
                t += 1
            out.append(str(t))
        return "\n".join(out)

    def _gen_q(rng, s, q):
        n = len(s)
        lines = [s, str(q)]
        for _ in range(q):
            lines.append(f"{rng.randint(1, n)} {rng.randint(1, n)}")
        return "\n".join(lines) + "\n"

    def g1(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(5, 20)), rng.randint(2, 6))

    def g2(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(50, 500), "abc"), rng.randint(10, 40))

    def g3(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(2000, 5000), "abcd"), rng.randint(30, 150))

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 20, Q ≤ 6", "points": 25, "constraint": "1 ≤ |S| ≤ 20; Q ≤ 6", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 500, Q ≤ 40", "points": 35, "constraint": "1 ≤ |S| ≤ 500; Q ≤ 40", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 5·10^3, Q ≤ 150", "points": 40, "constraint": "1 ≤ |S| ≤ 5·10^3; Q ≤ 150", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "So sánh ký tự từng vị trí.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "O(Q·|S|) đủ với |S| ≤ 500.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Binary search độ dài L + hash 2 đoạn để check bằng nhau → O(log |S|) mỗi query.", "starCost": 1},
    ]
    statement = (
        "Cho xâu S và Q truy vấn `(i, j)`. Tính độ dài tiền tố chung dài nhất (LCP) của hai hậu tố `S[i..]` và `S[j..]`.\n\n"
        "**Input**: dòng 1 = S; dòng 2 = Q; Q dòng (i, j) 1-indexed.\n\n"
        "**Output**: Q dòng, mỗi dòng 1 số nguyên.\n\n"
        "**Ràng buộc**: 1 ≤ |S| ≤ 5·10^3, 1 ≤ Q ≤ 150."
    )
    return base_problem(
        slug=slug, title="LCP của 2 hậu tố", title_en="LCP of Two Suffixes",
        topic_id="string-hash", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["string-hash", "binary-search"], statement=statement,
        vn_pattern="Binary search LCP + hash O(1).",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Binary search L = LCP. Với L cố định check hash(S[i..i+L-1]) == hash(S[j..j+L-1]).",
        sketch="// BS on length L; check hash equality at length L",
    )


def build_sh_palindrome_q():
    slug = "sh-palindrome-q"

    def solve(inp):
        lines = inp.strip("\n").split("\n")
        s = lines[0]
        q = int(lines[1])
        out = []
        for i in range(q):
            l, r = map(int, lines[2 + i].split())
            sub = s[l - 1:r]
            out.append("YES" if sub == sub[::-1] else "NO")
        return "\n".join(out)

    def _gen_q(rng, s, q):
        n = len(s)
        lines = [s, str(q)]
        for _ in range(q):
            l = rng.randint(1, n)
            r = rng.randint(l, n)
            lines.append(f"{l} {r}")
        return "\n".join(lines) + "\n"

    def g1(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(5, 20)), rng.randint(2, 8))

    def g2(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(50, 500), "abc"), rng.randint(10, 50))

    def g3(rng):
        return _gen_q(rng, _rand_str(rng, rng.randint(2000, 5000), "abcd"), rng.randint(50, 200))

    subtasks = [
        {"id": "st1", "title": "|S| ≤ 20, Q ≤ 8", "points": 25, "constraint": "1 ≤ |S| ≤ 20; Q ≤ 8", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "|S| ≤ 500, Q ≤ 50", "points": 35, "constraint": "1 ≤ |S| ≤ 500; Q ≤ 50", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "|S| ≤ 5·10^3, Q ≤ 200", "points": 40, "constraint": "1 ≤ |S| ≤ 5·10^3; Q ≤ 200", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Cắt đoạn rồi check palindrome bằng 2 con trỏ.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Vẫn 2 con trỏ O(|S|) mỗi query.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Hash tiến và hash của reverse(S), so 2 hash đoạn O(1).", "starCost": 1},
    ]
    statement = (
        "Cho xâu S và Q truy vấn `(l, r)`. Với mỗi truy vấn, kiểm tra `S[l..r]` có phải xâu palindrome.\n\n"
        "**Input**: dòng 1 = S; dòng 2 = Q; Q dòng (l, r) 1-indexed.\n\n"
        "**Output**: Q dòng `YES` / `NO`.\n\n"
        "**Ràng buộc**: 1 ≤ |S| ≤ 5·10^3, 1 ≤ Q ≤ 200."
    )
    return base_problem(
        slug=slug, title="Palindrome theo truy vấn", title_en="Range Palindrome Queries",
        topic_id="string-hash", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["string-hash", "palindrome"], statement=statement,
        vn_pattern="So sánh hash tiến vs hash lùi của đoạn.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="Tính prefix-hash của S và prefix-hash của reverse(S). Đoạn [l..r] là palindrome ⇔ hash đoạn tiến == hash đoạn lùi tương ứng.",
        sketch="// h_fwd vs h_rev → O(1) palindrome check",
    )


# ---------------------------------------------------------------------------
# Tree DP problems (tdp-*) — topic = tree-dp-intro
# Trees are rooted at node 1; input format: N, then N-1 edges (u v)
# ---------------------------------------------------------------------------
def _gen_tree(rng, n):
    """Random tree on N nodes; return list of (u, v) edges (1-indexed)."""
    edges = []
    for v in range(2, n + 1):
        u = rng.randint(1, v - 1)
        edges.append((u, v))
    return edges


def _read_tree(inp):
    toks = inp.split()
    n = int(toks[0])
    adj = [[] for _ in range(n + 1)]
    idx = 1
    for _ in range(n - 1):
        u = int(toks[idx]); v = int(toks[idx + 1]); idx += 2
        adj[u].append(v)
        adj[v].append(u)
    return n, adj, toks, idx


def _iter_dfs_order(n, adj, root=1):
    """Return BFS order + parent array (iterative, safe for big N)."""
    order = [root]
    parent = [0] * (n + 1)
    parent[root] = -1
    head = 0
    while head < len(order):
        u = order[head]; head += 1
        for v in adj[u]:
            if v != parent[u]:
                parent[v] = u
                order.append(v)
    return order, parent


def build_tdp_subtree_size():
    slug = "tdp-subtree-size"

    def solve(inp):
        n, adj, _, _ = _read_tree(inp)
        order, parent = _iter_dfs_order(n, adj)
        sz = [1] * (n + 1)
        for u in reversed(order):
            if parent[u] != -1:
                sz[parent[u]] += sz[u]
        return " ".join(str(sz[i]) for i in range(1, n + 1))

    def _emit(rng, n):
        edges = _gen_tree(rng, n)
        return f"{n}\n" + "\n".join(f"{u} {v}" for u, v in edges) + "\n"

    def g1(rng):
        return _emit(rng, rng.randint(3, 8))

    def g2(rng):
        return _emit(rng, rng.randint(20, 100))

    def g3(rng):
        return _emit(rng, rng.randint(500, 1000))

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000", "points": 40, "constraint": "1 ≤ N ≤ 1000", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "DFS đệ quy, đếm các node trong subtree.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "size[u] = 1 + Σ size[c] với c là con.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Cẩn thận stack: dùng DFS iterative khi N lớn.", "starCost": 1},
    ]
    statement = (
        "Cho cây có gốc 1 với N đỉnh và N-1 cạnh. Với mỗi đỉnh `u`, in kích thước cây con gốc `u`.\n\n"
        "**Input**: dòng 1 = N; N-1 dòng tiếp theo, mỗi dòng 2 số `u v` mô tả cạnh.\n\n"
        "**Output**: 1 dòng gồm N số: `size[1] size[2] ... size[N]`.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000."
    )
    return base_problem(
        slug=slug, title="Kích thước cây con", title_en="Subtree Size",
        topic_id="tree-dp-intro", tier="T2", skills=["S4-Cài đặt"], difficulty=1,
        tags=["tree-dp", "dfs"], statement=statement,
        vn_pattern="DP đáy lên qua DFS.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="DFS từ gốc, sau khi quay lui từ con c: size[u] += size[c]. Cuối cùng size[u] = số node trong subtree.",
        sketch="// post-order DFS, size[u] = 1 + sum(size[child])",
    )


def build_tdp_subtree_sum():
    slug = "tdp-subtree-sum"

    def solve(inp):
        toks = inp.split()
        n = int(toks[0])
        a = [0] + [int(x) for x in toks[1:1 + n]]
        adj = [[] for _ in range(n + 1)]
        idx = 1 + n
        for _ in range(n - 1):
            u = int(toks[idx]); v = int(toks[idx + 1]); idx += 2
            adj[u].append(v); adj[v].append(u)
        order, parent = _iter_dfs_order(n, adj)
        s = a[:]
        for u in reversed(order):
            if parent[u] != -1:
                s[parent[u]] += s[u]
        return " ".join(str(s[i]) for i in range(1, n + 1))

    def _emit(rng, n, vmax):
        a = [rng.randint(-vmax, vmax) for _ in range(n)]
        edges = _gen_tree(rng, n)
        return f"{n}\n{' '.join(map(str, a))}\n" + "\n".join(f"{u} {v}" for u, v in edges) + "\n"

    def g1(rng):
        return _emit(rng, rng.randint(3, 8), 10)

    def g2(rng):
        return _emit(rng, rng.randint(20, 100), 1000)

    def g3(rng):
        return _emit(rng, rng.randint(500, 1000), 1_000_000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8; |A_i| ≤ 10", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100; |A_i| ≤ 10^3", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000", "points": 40, "constraint": "1 ≤ N ≤ 1000; |A_i| ≤ 10^6", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "DFS subtree, cộng các giá trị.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "sum[u] = a[u] + Σ sum[c].", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "Lưu ý overflow — dùng long long.", "starCost": 1},
    ]
    statement = (
        "Cho cây có gốc 1 với N đỉnh, mỗi đỉnh có giá trị `A_i`. Với mỗi đỉnh `u`, in tổng các giá trị trong subtree gốc `u`.\n\n"
        "**Input**: dòng 1 = N; dòng 2 = N số `A_i`; N-1 dòng tiếp theo, mỗi dòng 2 số `u v`.\n\n"
        "**Output**: 1 dòng N số.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000, |A_i| ≤ 10^6."
    )
    return base_problem(
        slug=slug, title="Tổng giá trị cây con", title_en="Subtree Sum",
        topic_id="tree-dp-intro", tier="T2", skills=["S4-Cài đặt"], difficulty=1,
        tags=["tree-dp", "dfs"], statement=statement,
        vn_pattern="DP đáy lên cộng dồn.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="DFS post-order, sum[u] = a[u] + Σ sum[c]. Dùng long long phòng overflow.",
        sketch="// dfs(u): sum[u] = a[u]; for c in children: sum[u] += dfs(c)",
    )


def build_tdp_tree_diameter():
    slug = "tdp-tree-diameter"

    def solve(inp):
        n, adj, _, _ = _read_tree(inp)
        if n == 1:
            return "0"
        order, parent = _iter_dfs_order(n, adj)
        depth = [0] * (n + 1)
        best = [0] * (n + 1)  # longest path going down from u
        ans = 0
        for u in reversed(order):
            top1 = 0
            top2 = 0
            for c in adj[u]:
                if c == parent[u]:
                    continue
                d = best[c] + 1
                if d > top1:
                    top2 = top1
                    top1 = d
                elif d > top2:
                    top2 = d
            best[u] = top1
            if top1 + top2 > ans:
                ans = top1 + top2
        return str(ans)

    def _emit(rng, n):
        return f"{n}\n" + "\n".join(f"{u} {v}" for u, v in _gen_tree(rng, n)) + "\n"

    def g1(rng):
        return _emit(rng, rng.randint(2, 8))

    def g2(rng):
        return _emit(rng, rng.randint(20, 100))

    def g3(rng):
        return _emit(rng, rng.randint(500, 1000))

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000", "points": 40, "constraint": "1 ≤ N ≤ 1000", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Đường kính = max khoảng cách BFS hai lần.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "Hoặc DP: với mỗi đỉnh giữ 2 nhánh dài nhất xuống, cộng lại.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "best[u] = max nhánh con +1; diameter qua u = top1 + top2.", "starCost": 1},
    ]
    statement = (
        "Cho cây N đỉnh (không trọng số). Hãy tính **đường kính** — độ dài đường đi dài nhất giữa hai đỉnh (số cạnh).\n\n"
        "**Input**: dòng 1 = N; N-1 dòng tiếp theo, mỗi dòng 2 số `u v`.\n\n"
        "**Output**: 1 số nguyên.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000."
    )
    return base_problem(
        slug=slug, title="Đường kính cây", title_en="Tree Diameter",
        topic_id="tree-dp-intro", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=2,
        tags=["tree-dp", "diameter"], statement=statement,
        vn_pattern="DP nhánh dài nhất xuống.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="DP post-order. best[u] = 1 + max best[c]. Đường kính = max(top1[u] + top2[u]) khi xét mỗi u.",
        sketch="// post-order DFS, track top1, top2; ans = max(top1+top2)",
    )


def build_tdp_max_indep_set():
    slug = "tdp-max-indep-set"

    def solve(inp):
        toks = inp.split()
        n = int(toks[0])
        w = [0] + [int(x) for x in toks[1:1 + n]]
        adj = [[] for _ in range(n + 1)]
        idx = 1 + n
        for _ in range(n - 1):
            u = int(toks[idx]); v = int(toks[idx + 1]); idx += 2
            adj[u].append(v); adj[v].append(u)
        order, parent = _iter_dfs_order(n, adj)
        f0 = [0] * (n + 1)
        f1 = [0] * (n + 1)
        for u in reversed(order):
            f1[u] = w[u]
            for c in adj[u]:
                if c == parent[u]:
                    continue
                f0[u] += max(f0[c], f1[c])
                f1[u] += f0[c]
        return str(max(f0[1], f1[1]))

    def _emit(rng, n, vmax):
        w = [rng.randint(1, vmax) for _ in range(n)]
        return f"{n}\n{' '.join(map(str, w))}\n" + "\n".join(f"{u} {v}" for u, v in _gen_tree(rng, n)) + "\n"

    def g1(rng):
        return _emit(rng, rng.randint(2, 8), 50)

    def g2(rng):
        return _emit(rng, rng.randint(20, 100), 1000)

    def g3(rng):
        return _emit(rng, rng.randint(500, 1000), 1_000_000)

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8; W_i ≤ 50", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100; W_i ≤ 10^3", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000", "points": 40, "constraint": "1 ≤ N ≤ 1000; W_i ≤ 10^6", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Duyệt mọi tập độc lập (bitmask) cho N nhỏ.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "DP cây 2 trạng thái: f0[u], f1[u].", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "f0[u] = Σ max(f0[c], f1[c]); f1[u] = w[u] + Σ f0[c]; đáp số = max(f0[root], f1[root]).", "starCost": 1},
    ]
    statement = (
        "Cho cây N đỉnh, mỗi đỉnh có trọng số `W_i` ≥ 1. Hãy chọn một tập con các đỉnh sao cho **không có hai đỉnh kề** nào cùng được chọn, và tổng `W_i` lớn nhất. In tổng đó.\n\n"
        "**Input**: dòng 1 = N; dòng 2 = N số `W_i`; N-1 dòng tiếp theo, mỗi dòng 2 số `u v`.\n\n"
        "**Output**: 1 số nguyên.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000, 1 ≤ W_i ≤ 10^6."
    )
    return base_problem(
        slug=slug, title="Tập độc lập có trọng cực đại trên cây", title_en="Max Weighted Independent Set on Tree",
        topic_id="tree-dp-intro", tier="T2", skills=["S2-Phân tích", "S4-Cài đặt"], difficulty=3,
        tags=["tree-dp"], statement=statement,
        vn_pattern="DP 2 trạng thái lấy/không lấy.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="f0[u] = không lấy u, mỗi con c đóng góp max(f0[c], f1[c]). f1[u] = lấy u (= w[u]), con không được lấy nên đóng góp f0[c]. Đáp số = max(f0[root], f1[root]).",
        sketch="// f0[u] = sum(max(f0[c], f1[c])); f1[u] = w[u] + sum(f0[c])",
    )


def build_tdp_subordinates():
    slug = "tdp-subordinates"

    def solve(inp):
        toks = inp.split()
        n = int(toks[0])
        adj = [[] for _ in range(n + 1)]
        for i in range(2, n + 1):
            b = int(toks[i - 2 + 1])  # toks[1] = boss of 2
            adj[b].append(i)
        # Iterative count of descendants
        cnt = [0] * (n + 1)
        order = [1]
        head = 0
        parent = [0] * (n + 1)
        parent[1] = -1
        while head < len(order):
            u = order[head]; head += 1
            for c in adj[u]:
                parent[c] = u
                order.append(c)
        for u in reversed(order):
            if parent[u] != -1:
                cnt[parent[u]] += cnt[u] + 1
        return " ".join(str(cnt[i]) for i in range(1, n + 1))

    def _emit(rng, n):
        bosses = [rng.randint(1, i - 1) for i in range(2, n + 1)]
        return f"{n}\n{' '.join(map(str, bosses))}\n"

    def g1(rng):
        return _emit(rng, rng.randint(3, 8))

    def g2(rng):
        return _emit(rng, rng.randint(20, 100))

    def g3(rng):
        return _emit(rng, rng.randint(500, 1000))

    subtasks = [
        {"id": "st1", "title": "N ≤ 8", "points": 25, "constraint": "1 ≤ N ≤ 8", "nCases": 5, "gen": g1},
        {"id": "st2", "title": "N ≤ 100", "points": 35, "constraint": "1 ≤ N ≤ 100", "nCases": 6, "gen": g2},
        {"id": "st3", "title": "N ≤ 1000", "points": 40, "constraint": "1 ≤ N ≤ 1000", "nCases": 6, "gen": g3},
    ]
    cases, samples = generate_cases(slug, subtasks, solve)
    for st in subtasks:
        del st["gen"]; del st["nCases"]
    hints = [
        {"id": f"{slug}-st1", "subtaskId": "st1", "content": "Duyệt subtree, đếm số node khác chính nó.", "starCost": 0},
        {"id": f"{slug}-st2", "subtaskId": "st2", "content": "cnt[u] = Σ (cnt[c] + 1) với mọi con c.", "starCost": 1},
        {"id": f"{slug}-st3", "subtaskId": "st3", "content": "DFS post-order; iterative khi N lớn.", "starCost": 1},
    ]
    statement = (
        "Cho một công ty N nhân viên đánh số `1..N`. Nhân viên `1` là sếp tổng. Mỗi nhân viên `i ≥ 2` có cấp trên trực tiếp `b_i < i`. Với mỗi nhân viên `u`, in **số nhân viên dưới quyền** (kể trực tiếp + gián tiếp).\n\n"
        "**Input**: dòng 1 = N; dòng 2 = N-1 số `b_2, b_3, ..., b_N`.\n\n"
        "**Output**: 1 dòng N số.\n\n"
        "**Ràng buộc**: 1 ≤ N ≤ 1000."
    )
    return base_problem(
        slug=slug, title="Đếm cấp dưới", title_en="Subordinates",
        topic_id="tree-dp-intro", tier="T2", skills=["S4-Cài đặt"], difficulty=2,
        tags=["tree-dp"], statement=statement,
        vn_pattern="DP đáy lên cộng kích thước con + 1.",
        subtasks=subtasks, samples=samples, test_cases=cases, hints=hints,
        editorial="DFS từ root 1. Sau khi xử lý xong các con c: cnt[u] += cnt[c] + 1. Mỗi cấp dưới gián tiếp được cộng đúng 1 lần qua cha gần nhất.",
        sketch="// post-order DFS; cnt[u] += cnt[c] + 1",
    )


# ---------------------------------------------------------------------------
# Topic → list of (slug, title, tier, skills) for roadmap injection
# ---------------------------------------------------------------------------
TOPIC_PROBLEMS = {
    "sieve-factorization": [
        ("sf-prime-table",     "Đếm số nguyên tố trong [L, R]",      "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("sf-spf-factorize",   "Phân tích thừa số bằng SPF",          "T2", ["S4-Cài đặt", "S2-Phân tích"]),
        ("sf-divisor-sum",     "Tổng các ước (σ)",                    "T2", ["S4-Cài đặt"]),
        ("sf-distinct-prime",  "Số ước nguyên tố khác nhau (ω)",      "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("sf-euler-phi",       "Hàm Euler φ(n)",                      "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "string-hash": [
        ("sh-pattern-count",   "Đếm số lần xuất hiện của mẫu",        "T2", ["S4-Cài đặt", "S2-Phân tích"]),
        ("sh-distinct-len-k",  "Số xâu con khác nhau độ dài K",       "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("sh-substring-eq",    "So khớp 2 đoạn xâu",                  "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("sh-lcp-pair",        "LCP của 2 hậu tố",                    "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("sh-palindrome-q",    "Palindrome theo truy vấn",            "T2", ["S2-Phân tích", "S4-Cài đặt"]),
    ],
    "tree-dp-intro": [
        ("tdp-subtree-size",   "Kích thước cây con",                  "T2", ["S4-Cài đặt"]),
        ("tdp-subtree-sum",    "Tổng giá trị cây con",                "T2", ["S4-Cài đặt"]),
        ("tdp-tree-diameter",  "Đường kính cây",                      "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("tdp-max-indep-set",  "Tập độc lập có trọng cực đại trên cây", "T2", ["S2-Phân tích", "S4-Cài đặt"]),
        ("tdp-subordinates",   "Đếm cấp dưới",                        "T2", ["S4-Cài đặt"]),
    ],
}


def patch_roadmap():
    """Inject the new problem slugs into the empty roadmap nodes."""
    data = json.loads(ROADMAP.read_text(encoding="utf-8"))
    touched = 0
    for node in data["nodes"]:
        if node["id"] in TOPIC_PROBLEMS:
            slugs = [s for (s, _, _, _) in TOPIC_PROBLEMS[node["id"]]]
            node["problems"] = slugs
            touched += 1
    ROADMAP.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[roadmap] patched {touched} nodes")


def rebuild_index():
    """Deterministically rebuild public/data/problems/index.json from filesystem."""
    slugs = sorted(p.stem for p in PROBLEMS_DIR.glob("*.json") if p.name != "index.json")
    INDEX.write_text(
        json.dumps(slugs, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[index] wrote {len(slugs)} slugs to {INDEX.relative_to(ROOT)}")


def main():
    if not PROBLEMS_DIR.exists():
        print(f"ERROR: {PROBLEMS_DIR} not found", file=sys.stderr)
        sys.exit(1)

    builders = [
        # sieve-factorization
        build_sf_prime_table,
        build_sf_spf_factorize,
        build_sf_divisor_sum,
        build_sf_distinct_prime,
        build_sf_euler_phi,
        # string-hash
        build_sh_pattern_count,
        build_sh_distinct_len_k,
        build_sh_substring_eq,
        build_sh_lcp_pair,
        build_sh_palindrome_q,
        # tree-dp-intro
        build_tdp_subtree_size,
        build_tdp_subtree_sum,
        build_tdp_tree_diameter,
        build_tdp_max_indep_set,
        build_tdp_subordinates,
    ]
    for fn in builders:
        prob = fn()
        write_problem(prob)
        n_cases = len(prob["testCases"])
        n_subs = len(prob["subtasks"])
        print(f"[ok] {prob['slug']:24s}  subtasks={n_subs} testCases={n_cases}")

    patch_roadmap()
    rebuild_index()
    print("done.")


if __name__ == "__main__":
    main()
